//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="FDR Web ServiceSoap", Namespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
    "vityManagement/xml/schemas/version/1.0")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DataAccessObject))]
public partial class FDRWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetListOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetEntityOperationCompleted;
    
    private System.Threading.SendOrPostCallback AddNewEntityOperationCompleted;
    
    private System.Threading.SendOrPostCallback AddNewMneOperationCompleted;
    
    private System.Threading.SendOrPostCallback EnquireOperationCompleted;
    
    /// <remarks/>
    public FDRWebService() {
        this.Url = "http://localhost/FDR/mnelistservice.asmx";
    }
    
    /// <remarks/>
    public event GetListCompletedEventHandler GetListCompleted;
    
    /// <remarks/>
    public event GetEntityCompletedEventHandler GetEntityCompleted;
    
    /// <remarks/>
    public event AddNewEntityCompletedEventHandler AddNewEntityCompleted;
    
    /// <remarks/>
    public event AddNewMneCompletedEventHandler AddNewMneCompleted;
    
    /// <remarks/>
    public event EnquireCompletedEventHandler EnquireCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
        "vityManagement/xml/schemas/version/1.0/GetList", RequestNamespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
        "vityManagement/xml/schemas/version/1.0", ResponseNamespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
        "vityManagement/xml/schemas/version/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public MultiNationalEntity[] GetList() {
        object[] results = this.Invoke("GetList", new object[0]);
        return ((MultiNationalEntity[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetList(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetList", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public MultiNationalEntity[] EndGetList(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((MultiNationalEntity[])(results[0]));
    }
    
    /// <remarks/>
    public void GetListAsync() {
        this.GetListAsync(null);
    }
    
    /// <remarks/>
    public void GetListAsync(object userState) {
        if ((this.GetListOperationCompleted == null)) {
            this.GetListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListOperationCompleted);
        }
        this.InvokeAsync("GetList", new object[0], this.GetListOperationCompleted, userState);
    }
    
    private void OnGetListOperationCompleted(object arg) {
        if ((this.GetListCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetListCompleted(this, new GetListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
        "vityManagement/xml/schemas/version/1.0/GetEntity", RequestNamespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
        "vityManagement/xml/schemas/version/1.0", ResponseNamespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
        "vityManagement/xml/schemas/version/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public MultiNationalEntity GetEntity(string taxRefNo) {
        object[] results = this.Invoke("GetEntity", new object[] {
                    taxRefNo});
        return ((MultiNationalEntity)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetEntity(string taxRefNo, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetEntity", new object[] {
                    taxRefNo}, callback, asyncState);
    }
    
    /// <remarks/>
    public MultiNationalEntity EndGetEntity(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((MultiNationalEntity)(results[0]));
    }
    
    /// <remarks/>
    public void GetEntityAsync(string taxRefNo) {
        this.GetEntityAsync(taxRefNo, null);
    }
    
    /// <remarks/>
    public void GetEntityAsync(string taxRefNo, object userState) {
        if ((this.GetEntityOperationCompleted == null)) {
            this.GetEntityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEntityOperationCompleted);
        }
        this.InvokeAsync("GetEntity", new object[] {
                    taxRefNo}, this.GetEntityOperationCompleted, userState);
    }
    
    private void OnGetEntityOperationCompleted(object arg) {
        if ((this.GetEntityCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetEntityCompleted(this, new GetEntityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
        "vityManagement/xml/schemas/version/1.0/AddNewEntity", RequestNamespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
        "vityManagement/xml/schemas/version/1.0", ResponseNamespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
        "vityManagement/xml/schemas/version/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int AddNewEntity(MultiNationalEntity mne) {
        object[] results = this.Invoke("AddNewEntity", new object[] {
                    mne});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginAddNewEntity(MultiNationalEntity mne, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("AddNewEntity", new object[] {
                    mne}, callback, asyncState);
    }
    
    /// <remarks/>
    public int EndAddNewEntity(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void AddNewEntityAsync(MultiNationalEntity mne) {
        this.AddNewEntityAsync(mne, null);
    }
    
    /// <remarks/>
    public void AddNewEntityAsync(MultiNationalEntity mne, object userState) {
        if ((this.AddNewEntityOperationCompleted == null)) {
            this.AddNewEntityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddNewEntityOperationCompleted);
        }
        this.InvokeAsync("AddNewEntity", new object[] {
                    mne}, this.AddNewEntityOperationCompleted, userState);
    }
    
    private void OnAddNewEntityOperationCompleted(object arg) {
        if ((this.AddNewEntityCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AddNewEntityCompleted(this, new AddNewEntityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
        "vityManagement/xml/schemas/version/1.0/AddNewMne", RequestNamespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
        "vityManagement/xml/schemas/version/1.0", ResponseNamespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
        "vityManagement/xml/schemas/version/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int AddNewMne(decimal partyId, string taxpayerReferenceNumber, int yearofAssessment, string registeredName, string tradingName, string registrationNumber, System.DateTime financialYearEnd, decimal turnoverAmount, string nameUltimateHoldingCo, string ultimateHoldingCompanyResOutSaInd, string taxResidencyCountryCodeUltimateHoldingCompany, string ultimateHoldingCoIncomeTaxRefNo, string masterLocalFileRequiredInd, string cbCReportRequiredInd, System.DateTime datestamp) {
        object[] results = this.Invoke("AddNewMne", new object[] {
                    partyId,
                    taxpayerReferenceNumber,
                    yearofAssessment,
                    registeredName,
                    tradingName,
                    registrationNumber,
                    financialYearEnd,
                    turnoverAmount,
                    nameUltimateHoldingCo,
                    ultimateHoldingCompanyResOutSaInd,
                    taxResidencyCountryCodeUltimateHoldingCompany,
                    ultimateHoldingCoIncomeTaxRefNo,
                    masterLocalFileRequiredInd,
                    cbCReportRequiredInd,
                    datestamp});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginAddNewMne(
                decimal partyId, 
                string taxpayerReferenceNumber, 
                int yearofAssessment, 
                string registeredName, 
                string tradingName, 
                string registrationNumber, 
                System.DateTime financialYearEnd, 
                decimal turnoverAmount, 
                string nameUltimateHoldingCo, 
                string ultimateHoldingCompanyResOutSaInd, 
                string taxResidencyCountryCodeUltimateHoldingCompany, 
                string ultimateHoldingCoIncomeTaxRefNo, 
                string masterLocalFileRequiredInd, 
                string cbCReportRequiredInd, 
                System.DateTime datestamp, 
                System.AsyncCallback callback, 
                object asyncState) {
        return this.BeginInvoke("AddNewMne", new object[] {
                    partyId,
                    taxpayerReferenceNumber,
                    yearofAssessment,
                    registeredName,
                    tradingName,
                    registrationNumber,
                    financialYearEnd,
                    turnoverAmount,
                    nameUltimateHoldingCo,
                    ultimateHoldingCompanyResOutSaInd,
                    taxResidencyCountryCodeUltimateHoldingCompany,
                    ultimateHoldingCoIncomeTaxRefNo,
                    masterLocalFileRequiredInd,
                    cbCReportRequiredInd,
                    datestamp}, callback, asyncState);
    }
    
    /// <remarks/>
    public int EndAddNewMne(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void AddNewMneAsync(decimal partyId, string taxpayerReferenceNumber, int yearofAssessment, string registeredName, string tradingName, string registrationNumber, System.DateTime financialYearEnd, decimal turnoverAmount, string nameUltimateHoldingCo, string ultimateHoldingCompanyResOutSaInd, string taxResidencyCountryCodeUltimateHoldingCompany, string ultimateHoldingCoIncomeTaxRefNo, string masterLocalFileRequiredInd, string cbCReportRequiredInd, System.DateTime datestamp) {
        this.AddNewMneAsync(partyId, taxpayerReferenceNumber, yearofAssessment, registeredName, tradingName, registrationNumber, financialYearEnd, turnoverAmount, nameUltimateHoldingCo, ultimateHoldingCompanyResOutSaInd, taxResidencyCountryCodeUltimateHoldingCompany, ultimateHoldingCoIncomeTaxRefNo, masterLocalFileRequiredInd, cbCReportRequiredInd, datestamp, null);
    }
    
    /// <remarks/>
    public void AddNewMneAsync(
                decimal partyId, 
                string taxpayerReferenceNumber, 
                int yearofAssessment, 
                string registeredName, 
                string tradingName, 
                string registrationNumber, 
                System.DateTime financialYearEnd, 
                decimal turnoverAmount, 
                string nameUltimateHoldingCo, 
                string ultimateHoldingCompanyResOutSaInd, 
                string taxResidencyCountryCodeUltimateHoldingCompany, 
                string ultimateHoldingCoIncomeTaxRefNo, 
                string masterLocalFileRequiredInd, 
                string cbCReportRequiredInd, 
                System.DateTime datestamp, 
                object userState) {
        if ((this.AddNewMneOperationCompleted == null)) {
            this.AddNewMneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddNewMneOperationCompleted);
        }
        this.InvokeAsync("AddNewMne", new object[] {
                    partyId,
                    taxpayerReferenceNumber,
                    yearofAssessment,
                    registeredName,
                    tradingName,
                    registrationNumber,
                    financialYearEnd,
                    turnoverAmount,
                    nameUltimateHoldingCo,
                    ultimateHoldingCompanyResOutSaInd,
                    taxResidencyCountryCodeUltimateHoldingCompany,
                    ultimateHoldingCoIncomeTaxRefNo,
                    masterLocalFileRequiredInd,
                    cbCReportRequiredInd,
                    datestamp}, this.AddNewMneOperationCompleted, userState);
    }
    
    private void OnAddNewMneOperationCompleted(object arg) {
        if ((this.AddNewMneCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AddNewMneCompleted(this, new AddNewMneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
        "vityManagement/xml/schemas/version/1.0/Enquire", RequestNamespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
        "vityManagement/xml/schemas/version/1.0", ResponseNamespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
        "vityManagement/xml/schemas/version/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ThirdPartyDataActivityManagementResponse Enquire(string taxrefno) {
        object[] results = this.Invoke("Enquire", new object[] {
                    taxrefno});
        return ((ThirdPartyDataActivityManagementResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginEnquire(string taxrefno, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Enquire", new object[] {
                    taxrefno}, callback, asyncState);
    }
    
    /// <remarks/>
    public ThirdPartyDataActivityManagementResponse EndEnquire(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ThirdPartyDataActivityManagementResponse)(results[0]));
    }
    
    /// <remarks/>
    public void EnquireAsync(string taxrefno) {
        this.EnquireAsync(taxrefno, null);
    }
    
    /// <remarks/>
    public void EnquireAsync(string taxrefno, object userState) {
        if ((this.EnquireOperationCompleted == null)) {
            this.EnquireOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnquireOperationCompleted);
        }
        this.InvokeAsync("Enquire", new object[] {
                    taxrefno}, this.EnquireOperationCompleted, userState);
    }
    
    private void OnEnquireOperationCompleted(object arg) {
        if ((this.EnquireCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.EnquireCompleted(this, new EnquireCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
    "vityManagement/xml/schemas/version/1.0")]
public partial class MultiNationalEntity : DataAccessObject {
    
    private decimal idField;
    
    private System.DateTime timestampField;
    
    private System.Nullable<decimal> partyIdField;
    
    private string taxpayerReferenceNumberField;
    
    private System.Nullable<int> yearofAssessmentField;
    
    private string registeredNameField;
    
    private string tradingNameField;
    
    private string registrationNumberField;
    
    private System.Nullable<System.DateTime> financialYearEndField;
    
    private System.Nullable<decimal> turnoverAmountField;
    
    private string nameUltimateHoldingCoField;
    
    private string ultimateHoldingCompanyResOutSAIndField;
    
    private string taxResidencyCountryCodeUltimateHoldingCompanyField;
    
    private string ultimateHoldingCOIncomeTaxRefNoField;
    
    private string masterLocalFileRequiredIndField;
    
    private string cbCReportRequiredIndField;
    
    private System.Nullable<System.DateTime> datestampField;
    
    /// <remarks/>
    public decimal Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> PartyId {
        get {
            return this.partyIdField;
        }
        set {
            this.partyIdField = value;
        }
    }
    
    /// <remarks/>
    public string TaxpayerReferenceNumber {
        get {
            return this.taxpayerReferenceNumberField;
        }
        set {
            this.taxpayerReferenceNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> YearofAssessment {
        get {
            return this.yearofAssessmentField;
        }
        set {
            this.yearofAssessmentField = value;
        }
    }
    
    /// <remarks/>
    public string RegisteredName {
        get {
            return this.registeredNameField;
        }
        set {
            this.registeredNameField = value;
        }
    }
    
    /// <remarks/>
    public string TradingName {
        get {
            return this.tradingNameField;
        }
        set {
            this.tradingNameField = value;
        }
    }
    
    /// <remarks/>
    public string RegistrationNumber {
        get {
            return this.registrationNumberField;
        }
        set {
            this.registrationNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> FinancialYearEnd {
        get {
            return this.financialYearEndField;
        }
        set {
            this.financialYearEndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> TurnoverAmount {
        get {
            return this.turnoverAmountField;
        }
        set {
            this.turnoverAmountField = value;
        }
    }
    
    /// <remarks/>
    public string NameUltimateHoldingCo {
        get {
            return this.nameUltimateHoldingCoField;
        }
        set {
            this.nameUltimateHoldingCoField = value;
        }
    }
    
    /// <remarks/>
    public string UltimateHoldingCompanyResOutSAInd {
        get {
            return this.ultimateHoldingCompanyResOutSAIndField;
        }
        set {
            this.ultimateHoldingCompanyResOutSAIndField = value;
        }
    }
    
    /// <remarks/>
    public string TaxResidencyCountryCodeUltimateHoldingCompany {
        get {
            return this.taxResidencyCountryCodeUltimateHoldingCompanyField;
        }
        set {
            this.taxResidencyCountryCodeUltimateHoldingCompanyField = value;
        }
    }
    
    /// <remarks/>
    public string UltimateHoldingCOIncomeTaxRefNo {
        get {
            return this.ultimateHoldingCOIncomeTaxRefNoField;
        }
        set {
            this.ultimateHoldingCOIncomeTaxRefNoField = value;
        }
    }
    
    /// <remarks/>
    public string MasterLocalFileRequiredInd {
        get {
            return this.masterLocalFileRequiredIndField;
        }
        set {
            this.masterLocalFileRequiredIndField = value;
        }
    }
    
    /// <remarks/>
    public string CbCReportRequiredInd {
        get {
            return this.cbCReportRequiredIndField;
        }
        set {
            this.cbCReportRequiredIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> Datestamp {
        get {
            return this.datestampField;
        }
        set {
            this.datestampField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiNationalEntity))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
    "vityManagement/xml/schemas/version/1.0")]
public abstract partial class DataAccessObject {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +"vityManagement/xml/schemas/version/1.0")]
public partial class CbcReturnDetails {
    
    private string submitMasterAndLocalFileIndField;
    
    private string submitCbCDeclarationIndField;
    
    /// <remarks/>
    public string SubmitMasterAndLocalFileInd {
        get {
            return this.submitMasterAndLocalFileIndField;
        }
        set {
            this.submitMasterAndLocalFileIndField = value;
        }
    }
    
    /// <remarks/>
    public string SubmitCbCDeclarationInd {
        get {
            return this.submitCbCDeclarationIndField;
        }
        set {
            this.submitCbCDeclarationIndField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
    "vityManagement/xml/schemas/version/1.0")]
public partial class ThirdPartyDataActivityManagementResponse {
    
    private CbcReturnDetails cBCField;
    
    /// <remarks/>
    public CbcReturnDetails CBC {
        get {
            return this.cBCField;
        }
        set {
            this.cBCField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void GetListCompletedEventHandler(object sender, GetListCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public MultiNationalEntity[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((MultiNationalEntity[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void GetEntityCompletedEventHandler(object sender, GetEntityCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetEntityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetEntityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public MultiNationalEntity Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((MultiNationalEntity)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void AddNewEntityCompletedEventHandler(object sender, AddNewEntityCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AddNewEntityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal AddNewEntityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void AddNewMneCompletedEventHandler(object sender, AddNewMneCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AddNewMneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal AddNewMneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void EnquireCompletedEventHandler(object sender, EnquireCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class EnquireCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal EnquireCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ThirdPartyDataActivityManagementResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ThirdPartyDataActivityManagementResponse)(this.results[0]));
        }
    }
}
