//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
    "vityManagement/xml/schemas/version/1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
    "vityManagement/xml/schemas/version/1.0", IsNullable=false)]
public partial class ThirdPartyDataActivityManagementRequest {
    
    private ThirdPartyDataActivityManagementRequestRequestOperation requestOperationField;
    
    private string taxRefNoField;
    
    private ThirdPartyDataType dataTypeField;
    
    private string periodField;
    
    private string yearField;
    
    private System.DateTime dateField;
    
    private bool dateFieldSpecified;
    
    /// <remarks/>
    public ThirdPartyDataActivityManagementRequestRequestOperation RequestOperation {
        get {
            return this.requestOperationField;
        }
        set {
            this.requestOperationField = value;
        }
    }
    
    /// <remarks/>
    public string TaxRefNo {
        get {
            return this.taxRefNoField;
        }
        set {
            this.taxRefNoField = value;
        }
    }
    
    /// <remarks/>
    public ThirdPartyDataType DataType {
        get {
            return this.dataTypeField;
        }
        set {
            this.dataTypeField = value;
        }
    }
    
    /// <remarks/>
    public string Period {
        get {
            return this.periodField;
        }
        set {
            this.periodField = value;
        }
    }
    
    /// <remarks/>
    public string Year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DateSpecified {
        get {
            return this.dateFieldSpecified;
        }
        set {
            this.dateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
    "vityManagement/xml/schemas/version/1.0")]
public enum ThirdPartyDataActivityManagementRequestRequestOperation {
    
    /// <remarks/>
    ENQUIRE_ACTIVITY,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartySubmissionHeader/xml/sc" +
    "hemas/version/1.17")]
public enum ThirdPartyDataType {
    
    /// <remarks/>
    CBC,
    
    /// <remarks/>
    FTI,
    
    /// <remarks/>
    I3B,
    
    /// <remarks/>
    I3C,
    
    /// <remarks/>
    I3E,
    
    /// <remarks/>
    I3S,
    
    /// <remarks/>
    INS,
    
    /// <remarks/>
    IPR,
    
    /// <remarks/>
    MED,
    
    /// <remarks/>
    TCR,
    
    /// <remarks/>
    TCS,
    
    /// <remarks/>
    TPCB,
    
    /// <remarks/>
    VLL,
    
    /// <remarks/>
    VSL,
    
    /// <remarks/>
    WHD,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
    "vityManagement/xml/schemas/version/1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
    "vityManagement/xml/schemas/version/1.0", IsNullable=false)]
public partial class ThirdPartyDataActivityManagementResponse {
    
    private ThirdPartyDataActivityManagementResponseCBC cBCField;
    
    /// <remarks/>
    public ThirdPartyDataActivityManagementResponseCBC CBC {
        get {
            return this.cBCField;
        }
        set {
            this.cBCField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartyData/ThirdPartyDataActi" +
    "vityManagement/xml/schemas/version/1.0")]
public partial class ThirdPartyDataActivityManagementResponseCBC {
    
    private YesNoIndType submitCbCDeclarationIndField;
    
    private YesNoIndType submitMasterAndLocalFileIndField;
    
    /// <remarks/>
    public YesNoIndType SubmitCbCDeclarationInd {
        get {
            return this.submitCbCDeclarationIndField;
        }
        set {
            this.submitCbCDeclarationIndField = value;
        }
    }
    
    /// <remarks/>
    public YesNoIndType SubmitMasterAndLocalFileInd {
        get {
            return this.submitMasterAndLocalFileIndField;
        }
        set {
            this.submitMasterAndLocalFileIndField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sars.gov.za/enterpriseMessagingModel/GMD/BaseTypes/xml/schemas/version" +
    "/55.2")]
public enum YesNoIndType {
    
    /// <remarks/>
    Y,
    
    /// <remarks/>
    N,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartySubmissionHeader/xml/sc" +
    "hemas/version/1.17")]
[System.Xml.Serialization.XmlRootAttribute("ThirdPartySubmissionHeader", Namespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartySubmissionHeader/xml/sc" +
    "hemas/version/1.17", IsNullable=false)]
public partial class ThirdPartySubmissionHeaderStructure {
    
    private ThirdPartySubmissionHeaderStructureSectionIdentifier sectionIdentifierField;
    
    private ThirdPartySubmissionHeaderStructureHeaderType headerTypeField;
    
    private System.DateTime messageCreateDateField;
    
    private int fileLayoutVersionField;
    
    private string uniqueFileIDField;
    
    private string sARSRequestReferenceField;
    
    private ThirdPartySubmissionHeaderStructureTestDataIndicator testDataIndicatorField;
    
    private ThirdPartyDataType dataTypeBeingSuppliedField;
    
    private ThirdPartySubmissionHeaderStructureChannelIdentifier channelIdentifierField;
    
    private string sourceIdentifierField;
    
    private string groupIDField;
    
    private int groupTotalField;
    
    private int uniqueGroupItemIDField;
    
    private string sourceSystemField;
    
    private string sourceSystemVersionField;
    
    private string contactPersonNameField;
    
    private string contactPersonSurnameField;
    
    private string businessTelephoneNumber1Field;
    
    private string businessTelephoneNumber2Field;
    
    private string cellPhoneNumberField;
    
    private string contactEmailField;
    
    /// <remarks/>
    public ThirdPartySubmissionHeaderStructureSectionIdentifier SectionIdentifier {
        get {
            return this.sectionIdentifierField;
        }
        set {
            this.sectionIdentifierField = value;
        }
    }
    
    /// <remarks/>
    public ThirdPartySubmissionHeaderStructureHeaderType HeaderType {
        get {
            return this.headerTypeField;
        }
        set {
            this.headerTypeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime MessageCreateDate {
        get {
            return this.messageCreateDateField;
        }
        set {
            this.messageCreateDateField = value;
        }
    }
    
    /// <remarks/>
    public int FileLayoutVersion {
        get {
            return this.fileLayoutVersionField;
        }
        set {
            this.fileLayoutVersionField = value;
        }
    }
    
    /// <remarks/>
    public string UniqueFileID {
        get {
            return this.uniqueFileIDField;
        }
        set {
            this.uniqueFileIDField = value;
        }
    }
    
    /// <remarks/>
    public string SARSRequestReference {
        get {
            return this.sARSRequestReferenceField;
        }
        set {
            this.sARSRequestReferenceField = value;
        }
    }
    
    /// <remarks/>
    public ThirdPartySubmissionHeaderStructureTestDataIndicator TestDataIndicator {
        get {
            return this.testDataIndicatorField;
        }
        set {
            this.testDataIndicatorField = value;
        }
    }
    
    /// <remarks/>
    public ThirdPartyDataType DataTypeBeingSupplied {
        get {
            return this.dataTypeBeingSuppliedField;
        }
        set {
            this.dataTypeBeingSuppliedField = value;
        }
    }
    
    /// <remarks/>
    public ThirdPartySubmissionHeaderStructureChannelIdentifier ChannelIdentifier {
        get {
            return this.channelIdentifierField;
        }
        set {
            this.channelIdentifierField = value;
        }
    }
    
    /// <remarks/>
    public string SourceIdentifier {
        get {
            return this.sourceIdentifierField;
        }
        set {
            this.sourceIdentifierField = value;
        }
    }
    
    /// <remarks/>
    public string GroupID {
        get {
            return this.groupIDField;
        }
        set {
            this.groupIDField = value;
        }
    }
    
    /// <remarks/>
    public int GroupTotal {
        get {
            return this.groupTotalField;
        }
        set {
            this.groupTotalField = value;
        }
    }
    
    /// <remarks/>
    public int UniqueGroupItemID {
        get {
            return this.uniqueGroupItemIDField;
        }
        set {
            this.uniqueGroupItemIDField = value;
        }
    }
    
    /// <remarks/>
    public string SourceSystem {
        get {
            return this.sourceSystemField;
        }
        set {
            this.sourceSystemField = value;
        }
    }
    
    /// <remarks/>
    public string SourceSystemVersion {
        get {
            return this.sourceSystemVersionField;
        }
        set {
            this.sourceSystemVersionField = value;
        }
    }
    
    /// <remarks/>
    public string ContactPersonName {
        get {
            return this.contactPersonNameField;
        }
        set {
            this.contactPersonNameField = value;
        }
    }
    
    /// <remarks/>
    public string ContactPersonSurname {
        get {
            return this.contactPersonSurnameField;
        }
        set {
            this.contactPersonSurnameField = value;
        }
    }
    
    /// <remarks/>
    public string BusinessTelephoneNumber1 {
        get {
            return this.businessTelephoneNumber1Field;
        }
        set {
            this.businessTelephoneNumber1Field = value;
        }
    }
    
    /// <remarks/>
    public string BusinessTelephoneNumber2 {
        get {
            return this.businessTelephoneNumber2Field;
        }
        set {
            this.businessTelephoneNumber2Field = value;
        }
    }
    
    /// <remarks/>
    public string CellPhoneNumber {
        get {
            return this.cellPhoneNumberField;
        }
        set {
            this.cellPhoneNumberField = value;
        }
    }
    
    /// <remarks/>
    public string ContactEmail {
        get {
            return this.contactEmailField;
        }
        set {
            this.contactEmailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartySubmissionHeader/xml/sc" +
    "hemas/version/1.17")]
public enum ThirdPartySubmissionHeaderStructureSectionIdentifier {
    
    /// <remarks/>
    H,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartySubmissionHeader/xml/sc" +
    "hemas/version/1.17")]
public enum ThirdPartySubmissionHeaderStructureHeaderType {
    
    /// <remarks/>
    GH,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartySubmissionHeader/xml/sc" +
    "hemas/version/1.17")]
public enum ThirdPartySubmissionHeaderStructureTestDataIndicator {
    
    /// <remarks/>
    T,
    
    /// <remarks/>
    L,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sars.gov.za/enterpriseMessagingModel/ThirdPartySubmissionHeader/xml/sc" +
    "hemas/version/1.17")]
public enum ThirdPartySubmissionHeaderStructureChannelIdentifier {
    
    /// <remarks/>
    CD,
    
    /// <remarks/>
    EFL,
    
    /// <remarks/>
    IFL,
    
    /// <remarks/>
    HTTPS,
    
    /// <remarks/>
    MQ,
}
