//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 
namespace FDRService.CbcStatusMessage {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oecd:ties:cbcstm:v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:oecd:ties:cbcstm:v1", IsNullable=false)]
    public partial class CbCStatusMessage_OECD {
        
        private MessageSpec_Type messageSpecField;
        
        private CbCMessageStatus_Type cbCStatusMessageField;
        
        private string versionField;
        
        public CbCStatusMessage_OECD() {
            this.versionField = "1.0";
        }
        
        /// <remarks/>
        public MessageSpec_Type MessageSpec {
            get {
                return this.messageSpecField;
            }
            set {
                this.messageSpecField = value;
            }
        }
        
        /// <remarks/>
        public CbCMessageStatus_Type CbCStatusMessage {
            get {
                return this.cbCStatusMessageField;
            }
            set {
                this.cbCStatusMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:cbcstm:v1")]
    public partial class MessageSpec_Type {
        
        private string sendingCompanyINField;
        
        private CountryCode_Type transmittingCountryField;
        
        private CountryCode_Type receivingCountryField;
        
        private MessageType_EnumType messageTypeField;
        
        private string warningField;
        
        private string contactField;
        
        private string messageRefIdField;
        
        private CbCMessageTypeIndic_EnumType messageTypeIndicField;
        
        private bool messageTypeIndicFieldSpecified;
        
        private string[] corrMessageRefIdField;
        
        private System.DateTime reportingPeriodField;
        
        private bool reportingPeriodFieldSpecified;
        
        private System.DateTime timestampField;
        
        /// <remarks/>
        public string SendingCompanyIN {
            get {
                return this.sendingCompanyINField;
            }
            set {
                this.sendingCompanyINField = value;
            }
        }
        
        /// <remarks/>
        public CountryCode_Type TransmittingCountry {
            get {
                return this.transmittingCountryField;
            }
            set {
                this.transmittingCountryField = value;
            }
        }
        
        /// <remarks/>
        public CountryCode_Type ReceivingCountry {
            get {
                return this.receivingCountryField;
            }
            set {
                this.receivingCountryField = value;
            }
        }
        
        /// <remarks/>
        public MessageType_EnumType MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Warning {
            get {
                return this.warningField;
            }
            set {
                this.warningField = value;
            }
        }
        
        /// <remarks/>
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public string MessageRefId {
            get {
                return this.messageRefIdField;
            }
            set {
                this.messageRefIdField = value;
            }
        }
        
        /// <remarks/>
        public CbCMessageTypeIndic_EnumType MessageTypeIndic {
            get {
                return this.messageTypeIndicField;
            }
            set {
                this.messageTypeIndicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MessageTypeIndicSpecified {
            get {
                return this.messageTypeIndicFieldSpecified;
            }
            set {
                this.messageTypeIndicFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CorrMessageRefId")]
        public string[] CorrMessageRefId {
            get {
                return this.corrMessageRefIdField;
            }
            set {
                this.corrMessageRefIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ReportingPeriod {
            get {
                return this.reportingPeriodField;
            }
            set {
                this.reportingPeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReportingPeriodSpecified {
            get {
                return this.reportingPeriodFieldSpecified;
            }
            set {
                this.reportingPeriodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:cbcstm:isostmtypes:v1")]
    public enum CountryCode_Type {
        
        /// <remarks/>
        AF,
        
        /// <remarks/>
        AX,
        
        /// <remarks/>
        AL,
        
        /// <remarks/>
        DZ,
        
        /// <remarks/>
        AS,
        
        /// <remarks/>
        AD,
        
        /// <remarks/>
        AO,
        
        /// <remarks/>
        AI,
        
        /// <remarks/>
        AQ,
        
        /// <remarks/>
        AG,
        
        /// <remarks/>
        AR,
        
        /// <remarks/>
        AM,
        
        /// <remarks/>
        AW,
        
        /// <remarks/>
        AU,
        
        /// <remarks/>
        AT,
        
        /// <remarks/>
        AZ,
        
        /// <remarks/>
        BS,
        
        /// <remarks/>
        BH,
        
        /// <remarks/>
        BD,
        
        /// <remarks/>
        BB,
        
        /// <remarks/>
        BY,
        
        /// <remarks/>
        BE,
        
        /// <remarks/>
        BZ,
        
        /// <remarks/>
        BJ,
        
        /// <remarks/>
        BM,
        
        /// <remarks/>
        BT,
        
        /// <remarks/>
        BO,
        
        /// <remarks/>
        BQ,
        
        /// <remarks/>
        BA,
        
        /// <remarks/>
        BW,
        
        /// <remarks/>
        BV,
        
        /// <remarks/>
        BR,
        
        /// <remarks/>
        IO,
        
        /// <remarks/>
        BN,
        
        /// <remarks/>
        BG,
        
        /// <remarks/>
        BF,
        
        /// <remarks/>
        BI,
        
        /// <remarks/>
        KH,
        
        /// <remarks/>
        CM,
        
        /// <remarks/>
        CA,
        
        /// <remarks/>
        CV,
        
        /// <remarks/>
        KY,
        
        /// <remarks/>
        CF,
        
        /// <remarks/>
        TD,
        
        /// <remarks/>
        CL,
        
        /// <remarks/>
        CN,
        
        /// <remarks/>
        CX,
        
        /// <remarks/>
        CC,
        
        /// <remarks/>
        CO,
        
        /// <remarks/>
        KM,
        
        /// <remarks/>
        CG,
        
        /// <remarks/>
        CD,
        
        /// <remarks/>
        CK,
        
        /// <remarks/>
        CR,
        
        /// <remarks/>
        CI,
        
        /// <remarks/>
        HR,
        
        /// <remarks/>
        CU,
        
        /// <remarks/>
        CW,
        
        /// <remarks/>
        CY,
        
        /// <remarks/>
        CZ,
        
        /// <remarks/>
        DK,
        
        /// <remarks/>
        DJ,
        
        /// <remarks/>
        DM,
        
        /// <remarks/>
        DO,
        
        /// <remarks/>
        EC,
        
        /// <remarks/>
        EG,
        
        /// <remarks/>
        SV,
        
        /// <remarks/>
        GQ,
        
        /// <remarks/>
        ER,
        
        /// <remarks/>
        EE,
        
        /// <remarks/>
        ET,
        
        /// <remarks/>
        FK,
        
        /// <remarks/>
        FO,
        
        /// <remarks/>
        FJ,
        
        /// <remarks/>
        FI,
        
        /// <remarks/>
        FR,
        
        /// <remarks/>
        GF,
        
        /// <remarks/>
        PF,
        
        /// <remarks/>
        TF,
        
        /// <remarks/>
        GA,
        
        /// <remarks/>
        GM,
        
        /// <remarks/>
        GE,
        
        /// <remarks/>
        DE,
        
        /// <remarks/>
        GH,
        
        /// <remarks/>
        GI,
        
        /// <remarks/>
        GR,
        
        /// <remarks/>
        GL,
        
        /// <remarks/>
        GD,
        
        /// <remarks/>
        GP,
        
        /// <remarks/>
        GU,
        
        /// <remarks/>
        GT,
        
        /// <remarks/>
        GG,
        
        /// <remarks/>
        GN,
        
        /// <remarks/>
        GW,
        
        /// <remarks/>
        GY,
        
        /// <remarks/>
        HT,
        
        /// <remarks/>
        HM,
        
        /// <remarks/>
        VA,
        
        /// <remarks/>
        HN,
        
        /// <remarks/>
        HK,
        
        /// <remarks/>
        HU,
        
        /// <remarks/>
        IS,
        
        /// <remarks/>
        IN,
        
        /// <remarks/>
        ID,
        
        /// <remarks/>
        IR,
        
        /// <remarks/>
        IQ,
        
        /// <remarks/>
        IE,
        
        /// <remarks/>
        IM,
        
        /// <remarks/>
        IL,
        
        /// <remarks/>
        IT,
        
        /// <remarks/>
        JM,
        
        /// <remarks/>
        JP,
        
        /// <remarks/>
        JE,
        
        /// <remarks/>
        JO,
        
        /// <remarks/>
        KZ,
        
        /// <remarks/>
        KE,
        
        /// <remarks/>
        KI,
        
        /// <remarks/>
        KP,
        
        /// <remarks/>
        KR,
        
        /// <remarks/>
        KW,
        
        /// <remarks/>
        KG,
        
        /// <remarks/>
        LA,
        
        /// <remarks/>
        LV,
        
        /// <remarks/>
        LB,
        
        /// <remarks/>
        LS,
        
        /// <remarks/>
        LR,
        
        /// <remarks/>
        LY,
        
        /// <remarks/>
        LI,
        
        /// <remarks/>
        LT,
        
        /// <remarks/>
        LU,
        
        /// <remarks/>
        MO,
        
        /// <remarks/>
        MK,
        
        /// <remarks/>
        MG,
        
        /// <remarks/>
        MW,
        
        /// <remarks/>
        MY,
        
        /// <remarks/>
        MV,
        
        /// <remarks/>
        ML,
        
        /// <remarks/>
        MT,
        
        /// <remarks/>
        MH,
        
        /// <remarks/>
        MQ,
        
        /// <remarks/>
        MR,
        
        /// <remarks/>
        MU,
        
        /// <remarks/>
        YT,
        
        /// <remarks/>
        MX,
        
        /// <remarks/>
        FM,
        
        /// <remarks/>
        MD,
        
        /// <remarks/>
        MC,
        
        /// <remarks/>
        MN,
        
        /// <remarks/>
        ME,
        
        /// <remarks/>
        MS,
        
        /// <remarks/>
        MA,
        
        /// <remarks/>
        MZ,
        
        /// <remarks/>
        MM,
        
        /// <remarks/>
        NA,
        
        /// <remarks/>
        NR,
        
        /// <remarks/>
        NP,
        
        /// <remarks/>
        NL,
        
        /// <remarks/>
        NC,
        
        /// <remarks/>
        NZ,
        
        /// <remarks/>
        NI,
        
        /// <remarks/>
        NE,
        
        /// <remarks/>
        NG,
        
        /// <remarks/>
        NU,
        
        /// <remarks/>
        NF,
        
        /// <remarks/>
        MP,
        
        /// <remarks/>
        NO,
        
        /// <remarks/>
        OM,
        
        /// <remarks/>
        PK,
        
        /// <remarks/>
        PW,
        
        /// <remarks/>
        PS,
        
        /// <remarks/>
        PA,
        
        /// <remarks/>
        PG,
        
        /// <remarks/>
        PY,
        
        /// <remarks/>
        PE,
        
        /// <remarks/>
        PH,
        
        /// <remarks/>
        PN,
        
        /// <remarks/>
        PL,
        
        /// <remarks/>
        PT,
        
        /// <remarks/>
        PR,
        
        /// <remarks/>
        QA,
        
        /// <remarks/>
        RE,
        
        /// <remarks/>
        RO,
        
        /// <remarks/>
        RU,
        
        /// <remarks/>
        RW,
        
        /// <remarks/>
        BL,
        
        /// <remarks/>
        SH,
        
        /// <remarks/>
        KN,
        
        /// <remarks/>
        LC,
        
        /// <remarks/>
        MF,
        
        /// <remarks/>
        PM,
        
        /// <remarks/>
        VC,
        
        /// <remarks/>
        WS,
        
        /// <remarks/>
        SM,
        
        /// <remarks/>
        ST,
        
        /// <remarks/>
        SA,
        
        /// <remarks/>
        SN,
        
        /// <remarks/>
        RS,
        
        /// <remarks/>
        SC,
        
        /// <remarks/>
        SL,
        
        /// <remarks/>
        SG,
        
        /// <remarks/>
        SX,
        
        /// <remarks/>
        SK,
        
        /// <remarks/>
        SI,
        
        /// <remarks/>
        SB,
        
        /// <remarks/>
        SO,
        
        /// <remarks/>
        ZA,
        
        /// <remarks/>
        GS,
        
        /// <remarks/>
        SS,
        
        /// <remarks/>
        ES,
        
        /// <remarks/>
        LK,
        
        /// <remarks/>
        SD,
        
        /// <remarks/>
        SR,
        
        /// <remarks/>
        SJ,
        
        /// <remarks/>
        SZ,
        
        /// <remarks/>
        SE,
        
        /// <remarks/>
        CH,
        
        /// <remarks/>
        SY,
        
        /// <remarks/>
        TW,
        
        /// <remarks/>
        TJ,
        
        /// <remarks/>
        TZ,
        
        /// <remarks/>
        TH,
        
        /// <remarks/>
        TL,
        
        /// <remarks/>
        TG,
        
        /// <remarks/>
        TK,
        
        /// <remarks/>
        TO,
        
        /// <remarks/>
        TT,
        
        /// <remarks/>
        TN,
        
        /// <remarks/>
        TR,
        
        /// <remarks/>
        TM,
        
        /// <remarks/>
        TC,
        
        /// <remarks/>
        TV,
        
        /// <remarks/>
        UG,
        
        /// <remarks/>
        UA,
        
        /// <remarks/>
        AE,
        
        /// <remarks/>
        GB,
        
        /// <remarks/>
        US,
        
        /// <remarks/>
        UM,
        
        /// <remarks/>
        UY,
        
        /// <remarks/>
        UZ,
        
        /// <remarks/>
        VU,
        
        /// <remarks/>
        VE,
        
        /// <remarks/>
        VN,
        
        /// <remarks/>
        VG,
        
        /// <remarks/>
        VI,
        
        /// <remarks/>
        WF,
        
        /// <remarks/>
        EH,
        
        /// <remarks/>
        YE,
        
        /// <remarks/>
        ZM,
        
        /// <remarks/>
        ZW,
        
        /// <remarks/>
        XK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:cbcstm:v1")]
    public enum MessageType_EnumType {
        
        /// <remarks/>
        CbCMessageStatus,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:cbcstm:v1")]
    public enum CbCMessageTypeIndic_EnumType {
        
        /// <remarks/>
        CbCMessageStatus,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:cbcstm:v1")]
    public partial class ValidationResult_Type {
        
        private FileAcceptanceStatus_EnumType statusField;
        
        private string[] validatedByField;
        
        /// <remarks/>
        public FileAcceptanceStatus_EnumType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ValidatedBy")]
        public string[] ValidatedBy {
            get {
                return this.validatedByField;
            }
            set {
                this.validatedByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:cbcstm:v1")]
    public enum FileAcceptanceStatus_EnumType {
        
        /// <remarks/>
        Accepted,
        
        /// <remarks/>
        Rejected,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:cbcstm:v1")]
    public partial class RecordError_Type {
        
        private string codeField;
        
        private ErrorDetail_Type detailsField;
        
        private string[] docRefIDInErrorField;
        
        private RecordError_TypeFieldsInError[] fieldsInErrorField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public ErrorDetail_Type Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DocRefIDInError")]
        public string[] DocRefIDInError {
            get {
                return this.docRefIDInErrorField;
            }
            set {
                this.docRefIDInErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FieldsInError")]
        public RecordError_TypeFieldsInError[] FieldsInError {
            get {
                return this.fieldsInErrorField;
            }
            set {
                this.fieldsInErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:cbcstm:v1")]
    public partial class ErrorDetail_Type {
        
        private LanguageCode_Type languageField;
        
        private bool languageFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LanguageCode_Type Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LanguageSpecified {
            get {
                return this.languageFieldSpecified;
            }
            set {
                this.languageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:cbcstm:isostmtypes:v1")]
    public enum LanguageCode_Type {
        
        /// <remarks/>
        AA,
        
        /// <remarks/>
        AB,
        
        /// <remarks/>
        AF,
        
        /// <remarks/>
        AK,
        
        /// <remarks/>
        SQ,
        
        /// <remarks/>
        AM,
        
        /// <remarks/>
        AR,
        
        /// <remarks/>
        AN,
        
        /// <remarks/>
        HY,
        
        /// <remarks/>
        AS,
        
        /// <remarks/>
        AV,
        
        /// <remarks/>
        AE,
        
        /// <remarks/>
        AY,
        
        /// <remarks/>
        AZ,
        
        /// <remarks/>
        BA,
        
        /// <remarks/>
        BM,
        
        /// <remarks/>
        EU,
        
        /// <remarks/>
        BE,
        
        /// <remarks/>
        BN,
        
        /// <remarks/>
        BH,
        
        /// <remarks/>
        BI,
        
        /// <remarks/>
        BS,
        
        /// <remarks/>
        BR,
        
        /// <remarks/>
        BG,
        
        /// <remarks/>
        MY,
        
        /// <remarks/>
        CA,
        
        /// <remarks/>
        CH,
        
        /// <remarks/>
        CE,
        
        /// <remarks/>
        ZH,
        
        /// <remarks/>
        CU,
        
        /// <remarks/>
        CV,
        
        /// <remarks/>
        KW,
        
        /// <remarks/>
        CO,
        
        /// <remarks/>
        CR,
        
        /// <remarks/>
        CS,
        
        /// <remarks/>
        DA,
        
        /// <remarks/>
        DV,
        
        /// <remarks/>
        NL,
        
        /// <remarks/>
        DZ,
        
        /// <remarks/>
        EN,
        
        /// <remarks/>
        EO,
        
        /// <remarks/>
        ET,
        
        /// <remarks/>
        EE,
        
        /// <remarks/>
        FO,
        
        /// <remarks/>
        FJ,
        
        /// <remarks/>
        FI,
        
        /// <remarks/>
        FR,
        
        /// <remarks/>
        FY,
        
        /// <remarks/>
        FF,
        
        /// <remarks/>
        KA,
        
        /// <remarks/>
        DE,
        
        /// <remarks/>
        GD,
        
        /// <remarks/>
        GA,
        
        /// <remarks/>
        GL,
        
        /// <remarks/>
        GV,
        
        /// <remarks/>
        EL,
        
        /// <remarks/>
        GN,
        
        /// <remarks/>
        GU,
        
        /// <remarks/>
        HT,
        
        /// <remarks/>
        HA,
        
        /// <remarks/>
        HE,
        
        /// <remarks/>
        HZ,
        
        /// <remarks/>
        HI,
        
        /// <remarks/>
        HO,
        
        /// <remarks/>
        HR,
        
        /// <remarks/>
        HU,
        
        /// <remarks/>
        IG,
        
        /// <remarks/>
        IS,
        
        /// <remarks/>
        IO,
        
        /// <remarks/>
        II,
        
        /// <remarks/>
        IU,
        
        /// <remarks/>
        IE,
        
        /// <remarks/>
        IA,
        
        /// <remarks/>
        ID,
        
        /// <remarks/>
        IK,
        
        /// <remarks/>
        IT,
        
        /// <remarks/>
        JV,
        
        /// <remarks/>
        JA,
        
        /// <remarks/>
        KL,
        
        /// <remarks/>
        KN,
        
        /// <remarks/>
        KS,
        
        /// <remarks/>
        KR,
        
        /// <remarks/>
        KK,
        
        /// <remarks/>
        KM,
        
        /// <remarks/>
        KI,
        
        /// <remarks/>
        RW,
        
        /// <remarks/>
        KY,
        
        /// <remarks/>
        KV,
        
        /// <remarks/>
        KG,
        
        /// <remarks/>
        KO,
        
        /// <remarks/>
        KJ,
        
        /// <remarks/>
        KU,
        
        /// <remarks/>
        LO,
        
        /// <remarks/>
        LA,
        
        /// <remarks/>
        LV,
        
        /// <remarks/>
        LI,
        
        /// <remarks/>
        LN,
        
        /// <remarks/>
        LT,
        
        /// <remarks/>
        LB,
        
        /// <remarks/>
        LU,
        
        /// <remarks/>
        LG,
        
        /// <remarks/>
        MK,
        
        /// <remarks/>
        MH,
        
        /// <remarks/>
        ML,
        
        /// <remarks/>
        MI,
        
        /// <remarks/>
        MR,
        
        /// <remarks/>
        MS,
        
        /// <remarks/>
        MG,
        
        /// <remarks/>
        MT,
        
        /// <remarks/>
        MN,
        
        /// <remarks/>
        NA,
        
        /// <remarks/>
        NV,
        
        /// <remarks/>
        NR,
        
        /// <remarks/>
        ND,
        
        /// <remarks/>
        NG,
        
        /// <remarks/>
        NE,
        
        /// <remarks/>
        NN,
        
        /// <remarks/>
        NB,
        
        /// <remarks/>
        NO,
        
        /// <remarks/>
        NY,
        
        /// <remarks/>
        OC,
        
        /// <remarks/>
        OJ,
        
        /// <remarks/>
        OR,
        
        /// <remarks/>
        OM,
        
        /// <remarks/>
        OS,
        
        /// <remarks/>
        PA,
        
        /// <remarks/>
        FA,
        
        /// <remarks/>
        PI,
        
        /// <remarks/>
        PL,
        
        /// <remarks/>
        PT,
        
        /// <remarks/>
        PS,
        
        /// <remarks/>
        QU,
        
        /// <remarks/>
        RM,
        
        /// <remarks/>
        RO,
        
        /// <remarks/>
        RN,
        
        /// <remarks/>
        RU,
        
        /// <remarks/>
        SG,
        
        /// <remarks/>
        SA,
        
        /// <remarks/>
        SI,
        
        /// <remarks/>
        SK,
        
        /// <remarks/>
        SL,
        
        /// <remarks/>
        SE,
        
        /// <remarks/>
        SM,
        
        /// <remarks/>
        SN,
        
        /// <remarks/>
        SD,
        
        /// <remarks/>
        SO,
        
        /// <remarks/>
        ST,
        
        /// <remarks/>
        ES,
        
        /// <remarks/>
        SC,
        
        /// <remarks/>
        SR,
        
        /// <remarks/>
        SS,
        
        /// <remarks/>
        SU,
        
        /// <remarks/>
        SW,
        
        /// <remarks/>
        SV,
        
        /// <remarks/>
        TY,
        
        /// <remarks/>
        TA,
        
        /// <remarks/>
        TT,
        
        /// <remarks/>
        TE,
        
        /// <remarks/>
        TG,
        
        /// <remarks/>
        TL,
        
        /// <remarks/>
        TH,
        
        /// <remarks/>
        BO,
        
        /// <remarks/>
        TI,
        
        /// <remarks/>
        TO,
        
        /// <remarks/>
        TN,
        
        /// <remarks/>
        TS,
        
        /// <remarks/>
        TK,
        
        /// <remarks/>
        TR,
        
        /// <remarks/>
        TW,
        
        /// <remarks/>
        UG,
        
        /// <remarks/>
        UK,
        
        /// <remarks/>
        UR,
        
        /// <remarks/>
        UZ,
        
        /// <remarks/>
        VE,
        
        /// <remarks/>
        VI,
        
        /// <remarks/>
        VO,
        
        /// <remarks/>
        CY,
        
        /// <remarks/>
        WA,
        
        /// <remarks/>
        WO,
        
        /// <remarks/>
        XH,
        
        /// <remarks/>
        YI,
        
        /// <remarks/>
        YO,
        
        /// <remarks/>
        ZA,
        
        /// <remarks/>
        ZU,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oecd:ties:cbcstm:v1")]
    public partial class RecordError_TypeFieldsInError {
        
        private string fieldPathField;
        
        /// <remarks/>
        public string FieldPath {
            get {
                return this.fieldPathField;
            }
            set {
                this.fieldPathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:cbcstm:v1")]
    public partial class FileError_Type {
        
        private string codeField;
        
        private ErrorDetail_Type detailsField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public ErrorDetail_Type Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:cbcstm:v1")]
    public partial class ValidationErrors_Type {
        
        private FileError_Type[] fileErrorField;
        
        private RecordError_Type[] recordErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FileError")]
        public FileError_Type[] FileError {
            get {
                return this.fileErrorField;
            }
            set {
                this.fileErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RecordError")]
        public RecordError_Type[] RecordError {
            get {
                return this.recordErrorField;
            }
            set {
                this.recordErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:cbcstm:v1")]
    public partial class FileMetaData_Type {
        
        private string cTSTransmissionIDField;
        
        private System.DateTime cTSSendingTimeStampField;
        
        private bool cTSSendingTimeStampFieldSpecified;
        
        private string uncompressedFileSizeKBQtyField;
        
        /// <remarks/>
        public string CTSTransmissionID {
            get {
                return this.cTSTransmissionIDField;
            }
            set {
                this.cTSTransmissionIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CTSSendingTimeStamp {
            get {
                return this.cTSSendingTimeStampField;
            }
            set {
                this.cTSSendingTimeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CTSSendingTimeStampSpecified {
            get {
                return this.cTSSendingTimeStampFieldSpecified;
            }
            set {
                this.cTSSendingTimeStampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string UncompressedFileSizeKBQty {
            get {
                return this.uncompressedFileSizeKBQtyField;
            }
            set {
                this.uncompressedFileSizeKBQtyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:cbcstm:v1")]
    public partial class OriginalMessage_Type {
        
        private string originalMessageRefIDField;
        
        private FileMetaData_Type fileMetaDataField;
        
        /// <remarks/>
        public string OriginalMessageRefID {
            get {
                return this.originalMessageRefIDField;
            }
            set {
                this.originalMessageRefIDField = value;
            }
        }
        
        /// <remarks/>
        public FileMetaData_Type FileMetaData {
            get {
                return this.fileMetaDataField;
            }
            set {
                this.fileMetaDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oecd:ties:cbcstm:v1")]
    public partial class CbCMessageStatus_Type {
        
        private OriginalMessage_Type originalMessageField;
        
        private ValidationErrors_Type validationErrorsField;
        
        private ValidationResult_Type validationResultField;
        
        /// <remarks/>
        public OriginalMessage_Type OriginalMessage {
            get {
                return this.originalMessageField;
            }
            set {
                this.originalMessageField = value;
            }
        }
        
        /// <remarks/>
        public ValidationErrors_Type ValidationErrors {
            get {
                return this.validationErrorsField;
            }
            set {
                this.validationErrorsField = value;
            }
        }
        
        /// <remarks/>
        public ValidationResult_Type ValidationResult {
            get {
                return this.validationResultField;
            }
            set {
                this.validationResultField = value;
            }
        }
    }
}
