//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sars.gov.za/GMD/StatusManagement/xml/schemas/version/1.14")]
[System.Xml.Serialization.XmlRootAttribute("StatusManagementRequest", Namespace="http://www.sars.gov.za/GMD/StatusManagement/xml/schemas/version/1.14", IsNullable=false)]
public partial class StatusManagementRequestStructure {
    
    private RequestOperationType requestOperationField;
    
    private string sourceChannelField;
    
    private ReferenceStructure referenceField;
    
    private SubReferenceStructure subReferenceField;
    
    private TaxYearRangeStructure taxYearRangeField;
    
    private TaxPeriodRangeStructure taxPeriodRangeField;
    
    private TaxDateRangeStructure taxDateRangeField;
    
    private TypeOfTaxType taxTypeField;
    
    private string dataTypeField;
    
    private StatusStructure statusDetailsField;
    
    /// <remarks/>
    public RequestOperationType RequestOperation {
        get {
            return this.requestOperationField;
        }
        set {
            this.requestOperationField = value;
        }
    }
    
    /// <remarks/>
    public string SourceChannel {
        get {
            return this.sourceChannelField;
        }
        set {
            this.sourceChannelField = value;
        }
    }
    
    /// <remarks/>
    public ReferenceStructure Reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
    
    /// <remarks/>
    public SubReferenceStructure SubReference {
        get {
            return this.subReferenceField;
        }
        set {
            this.subReferenceField = value;
        }
    }
    
    /// <remarks/>
    public TaxYearRangeStructure TaxYearRange {
        get {
            return this.taxYearRangeField;
        }
        set {
            this.taxYearRangeField = value;
        }
    }
    
    /// <remarks/>
    public TaxPeriodRangeStructure TaxPeriodRange {
        get {
            return this.taxPeriodRangeField;
        }
        set {
            this.taxPeriodRangeField = value;
        }
    }
    
    /// <remarks/>
    public TaxDateRangeStructure TaxDateRange {
        get {
            return this.taxDateRangeField;
        }
        set {
            this.taxDateRangeField = value;
        }
    }
    
    /// <remarks/>
    public TypeOfTaxType TaxType {
        get {
            return this.taxTypeField;
        }
        set {
            this.taxTypeField = value;
        }
    }
    
    /// <remarks/>
    public string DataType {
        get {
            return this.dataTypeField;
        }
        set {
            this.dataTypeField = value;
        }
    }
    
    /// <remarks/>
    public StatusStructure StatusDetails {
        get {
            return this.statusDetailsField;
        }
        set {
            this.statusDetailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sars.gov.za/GMD/StatusManagement/xml/schemas/version/1.14")]
public enum RequestOperationType {
    
    /// <remarks/>
    ENQUIRE_STATUS,
    
    /// <remarks/>
    UPDATE_STATUS,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sars.gov.za/GMD/StatusManagement/xml/schemas/version/1.14")]
public partial class ReferenceStructure {
    
    private ReferenceStructureIdentifier identifierField;
    
    private string[] valueField;
    
    /// <remarks/>
    public ReferenceStructureIdentifier Identifier {
        get {
            return this.identifierField;
        }
        set {
            this.identifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Value")]
    public string[] Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sars.gov.za/GMD/StatusManagement/xml/schemas/version/1.14")]
public enum ReferenceStructureIdentifier {
    
    /// <remarks/>
    TAX_REF_NO,
    
    /// <remarks/>
    CASE_NO,
    
    /// <remarks/>
    TRANSACTION_NO,
    
    /// <remarks/>
    PARTY_ID,
    
    /// <remarks/>
    ID_NO,
    
    /// <remarks/>
    PASSPORT_NO,
    
    /// <remarks/>
    SOURCE_IDENTIFIER,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sars.gov.za/GMD/StatusManagement/xml/schemas/version/1.14")]
public partial class FileStatusResultStructure {
    
    private string sourceIdentifierField;
    
    private System.DateTime messageCreateDateField;
    
    private System.DateTime transDateField;
    
    private bool transDateFieldSpecified;
    
    private string transPeriodField;
    
    private string transYearField;
    
    private string uniqueFileIDField;
    
    private string sARSRequestReferenceField;
    
    private string channelIdentifierField;
    
    private string fileResponseCodeField;
    
    private string fileResponseReasonField;
    
    private string totalNoOfSubmittedRecordsField;
    
    private string noOfAcceptedRecordsField;
    
    private string noOfRejectedRecordsField;
    
    private string noOfWarningAcceptedRecordsField;
    
    private string noOfDuplicatedRecordsField;
    
    private string taxRefNoField;
    
    /// <remarks/>
    public string SourceIdentifier {
        get {
            return this.sourceIdentifierField;
        }
        set {
            this.sourceIdentifierField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime MessageCreateDate {
        get {
            return this.messageCreateDateField;
        }
        set {
            this.messageCreateDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime TransDate {
        get {
            return this.transDateField;
        }
        set {
            this.transDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TransDateSpecified {
        get {
            return this.transDateFieldSpecified;
        }
        set {
            this.transDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string TransPeriod {
        get {
            return this.transPeriodField;
        }
        set {
            this.transPeriodField = value;
        }
    }
    
    /// <remarks/>
    public string TransYear {
        get {
            return this.transYearField;
        }
        set {
            this.transYearField = value;
        }
    }
    
    /// <remarks/>
    public string UniqueFileID {
        get {
            return this.uniqueFileIDField;
        }
        set {
            this.uniqueFileIDField = value;
        }
    }
    
    /// <remarks/>
    public string SARSRequestReference {
        get {
            return this.sARSRequestReferenceField;
        }
        set {
            this.sARSRequestReferenceField = value;
        }
    }
    
    /// <remarks/>
    public string ChannelIdentifier {
        get {
            return this.channelIdentifierField;
        }
        set {
            this.channelIdentifierField = value;
        }
    }
    
    /// <remarks/>
    public string FileResponseCode {
        get {
            return this.fileResponseCodeField;
        }
        set {
            this.fileResponseCodeField = value;
        }
    }
    
    /// <remarks/>
    public string FileResponseReason {
        get {
            return this.fileResponseReasonField;
        }
        set {
            this.fileResponseReasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string TotalNoOfSubmittedRecords {
        get {
            return this.totalNoOfSubmittedRecordsField;
        }
        set {
            this.totalNoOfSubmittedRecordsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NoOfAcceptedRecords {
        get {
            return this.noOfAcceptedRecordsField;
        }
        set {
            this.noOfAcceptedRecordsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NoOfRejectedRecords {
        get {
            return this.noOfRejectedRecordsField;
        }
        set {
            this.noOfRejectedRecordsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NoOfWarningAcceptedRecords {
        get {
            return this.noOfWarningAcceptedRecordsField;
        }
        set {
            this.noOfWarningAcceptedRecordsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NoOfDuplicatedRecords {
        get {
            return this.noOfDuplicatedRecordsField;
        }
        set {
            this.noOfDuplicatedRecordsField = value;
        }
    }
    
    /// <remarks/>
    public string TaxRefNo {
        get {
            return this.taxRefNoField;
        }
        set {
            this.taxRefNoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sars.gov.za/GMD/StatusManagement/xml/schemas/version/1.14")]
public partial class ProcessStatusItemStructure {
    
    private string processTypeField;
    
    private string processDescriptionField;
    
    private string caseStatusDescriptionField;
    
    private string reasonDescriptionField;
    
    private ProcessStatusItemStructureItemResolutionInd itemResolutionIndField;
    
    private bool itemResolutionIndFieldSpecified;
    
    private System.DateTime dateTimeCreatedField;
    
    private bool dateTimeCreatedFieldSpecified;
    
    private string usernameField;
    
    private string noteField;
    
    private string reasonCodeField;
    
    private string reasonValueField;
    
    /// <remarks/>
    public string ProcessType {
        get {
            return this.processTypeField;
        }
        set {
            this.processTypeField = value;
        }
    }
    
    /// <remarks/>
    public string ProcessDescription {
        get {
            return this.processDescriptionField;
        }
        set {
            this.processDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string CaseStatusDescription {
        get {
            return this.caseStatusDescriptionField;
        }
        set {
            this.caseStatusDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string ReasonDescription {
        get {
            return this.reasonDescriptionField;
        }
        set {
            this.reasonDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public ProcessStatusItemStructureItemResolutionInd ItemResolutionInd {
        get {
            return this.itemResolutionIndField;
        }
        set {
            this.itemResolutionIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ItemResolutionIndSpecified {
        get {
            return this.itemResolutionIndFieldSpecified;
        }
        set {
            this.itemResolutionIndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DateTimeCreated {
        get {
            return this.dateTimeCreatedField;
        }
        set {
            this.dateTimeCreatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DateTimeCreatedSpecified {
        get {
            return this.dateTimeCreatedFieldSpecified;
        }
        set {
            this.dateTimeCreatedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
    
    /// <remarks/>
    public string Note {
        get {
            return this.noteField;
        }
        set {
            this.noteField = value;
        }
    }
    
    /// <remarks/>
    public string ReasonCode {
        get {
            return this.reasonCodeField;
        }
        set {
            this.reasonCodeField = value;
        }
    }
    
    /// <remarks/>
    public string ReasonValue {
        get {
            return this.reasonValueField;
        }
        set {
            this.reasonValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sars.gov.za/GMD/StatusManagement/xml/schemas/version/1.14")]
public enum ProcessStatusItemStructureItemResolutionInd {
    
    /// <remarks/>
    GREEN,
    
    /// <remarks/>
    AMBER,
    
    /// <remarks/>
    RED,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sars.gov.za/GMD/StatusManagement/xml/schemas/version/1.14")]
public partial class ProcessStatusResultStructure {
    
    private string taxYearField;
    
    private string taxPeriodField;
    
    private System.DateTime taxDateField;
    
    private bool taxDateFieldSpecified;
    
    private ProcessStatusItemStructure[] processStatusItemsField;
    
    private decimal returnAmtField;
    
    private bool returnAmtFieldSpecified;
    
    private decimal accountAmtField;
    
    private bool accountAmtFieldSpecified;
    
    private string channelIdentifierField;
    
    /// <remarks/>
    public string TaxYear {
        get {
            return this.taxYearField;
        }
        set {
            this.taxYearField = value;
        }
    }
    
    /// <remarks/>
    public string TaxPeriod {
        get {
            return this.taxPeriodField;
        }
        set {
            this.taxPeriodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime TaxDate {
        get {
            return this.taxDateField;
        }
        set {
            this.taxDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TaxDateSpecified {
        get {
            return this.taxDateFieldSpecified;
        }
        set {
            this.taxDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ProcessStatusItem", IsNullable=false)]
    public ProcessStatusItemStructure[] ProcessStatusItems {
        get {
            return this.processStatusItemsField;
        }
        set {
            this.processStatusItemsField = value;
        }
    }
    
    /// <remarks/>
    public decimal ReturnAmt {
        get {
            return this.returnAmtField;
        }
        set {
            this.returnAmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReturnAmtSpecified {
        get {
            return this.returnAmtFieldSpecified;
        }
        set {
            this.returnAmtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal AccountAmt {
        get {
            return this.accountAmtField;
        }
        set {
            this.accountAmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AccountAmtSpecified {
        get {
            return this.accountAmtFieldSpecified;
        }
        set {
            this.accountAmtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string ChannelIdentifier {
        get {
            return this.channelIdentifierField;
        }
        set {
            this.channelIdentifierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sars.gov.za/GMD/StatusManagement/xml/schemas/version/1.14")]
public partial class WorkflowStatusResultStructure {
    
    private string taxYearField;
    
    private string taxPeriodField;
    
    private System.DateTime taxDateField;
    
    private bool taxDateFieldSpecified;
    
    private string trackingStatusShortCodeField;
    
    private string descriptionField;
    
    private System.DateTime dateTimeCreatedField;
    
    private string usernameField;
    
    private string noteField;
    
    private int revisionNumberField;
    
    private bool revisionNumberFieldSpecified;
    
    /// <remarks/>
    public string TaxYear {
        get {
            return this.taxYearField;
        }
        set {
            this.taxYearField = value;
        }
    }
    
    /// <remarks/>
    public string TaxPeriod {
        get {
            return this.taxPeriodField;
        }
        set {
            this.taxPeriodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime TaxDate {
        get {
            return this.taxDateField;
        }
        set {
            this.taxDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TaxDateSpecified {
        get {
            return this.taxDateFieldSpecified;
        }
        set {
            this.taxDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string TrackingStatusShortCode {
        get {
            return this.trackingStatusShortCodeField;
        }
        set {
            this.trackingStatusShortCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DateTimeCreated {
        get {
            return this.dateTimeCreatedField;
        }
        set {
            this.dateTimeCreatedField = value;
        }
    }
    
    /// <remarks/>
    public string Username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
    
    /// <remarks/>
    public string Note {
        get {
            return this.noteField;
        }
        set {
            this.noteField = value;
        }
    }
    
    /// <remarks/>
    public int RevisionNumber {
        get {
            return this.revisionNumberField;
        }
        set {
            this.revisionNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RevisionNumberSpecified {
        get {
            return this.revisionNumberFieldSpecified;
        }
        set {
            this.revisionNumberFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sars.gov.za/GMD/StatusManagement/xml/schemas/version/1.14")]
public partial class CaseStatusResultStructure {
    
    private string caseStatusCodeField;
    
    private string descriptionField;
    
    private System.DateTime dateTimeCreatedField;
    
    private bool dateTimeCreatedFieldSpecified;
    
    private string usernameField;
    
    private string noteField;
    
    private string parentCaseNoField;
    
    /// <remarks/>
    public string CaseStatusCode {
        get {
            return this.caseStatusCodeField;
        }
        set {
            this.caseStatusCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DateTimeCreated {
        get {
            return this.dateTimeCreatedField;
        }
        set {
            this.dateTimeCreatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DateTimeCreatedSpecified {
        get {
            return this.dateTimeCreatedFieldSpecified;
        }
        set {
            this.dateTimeCreatedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
    
    /// <remarks/>
    public string Note {
        get {
            return this.noteField;
        }
        set {
            this.noteField = value;
        }
    }
    
    /// <remarks/>
    public string ParentCaseNo {
        get {
            return this.parentCaseNoField;
        }
        set {
            this.parentCaseNoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sars.gov.za/GMD/StatusManagement/xml/schemas/version/1.14")]
public partial class StatusStructure {
    
    private string statusField;
    
    private string descriptionField;
    
    /// <remarks/>
    public string Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sars.gov.za/GMD/StatusManagement/xml/schemas/version/1.14")]
public partial class TaxDateRangeStructure {
    
    private System.DateTime fromTaxDateField;
    
    private System.DateTime toTaxDateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime FromTaxDate {
        get {
            return this.fromTaxDateField;
        }
        set {
            this.fromTaxDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ToTaxDate {
        get {
            return this.toTaxDateField;
        }
        set {
            this.toTaxDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sars.gov.za/GMD/StatusManagement/xml/schemas/version/1.14")]
public partial class TaxPeriodRangeStructure {
    
    private string fromTaxPeriodField;
    
    private string toTaxPeriodField;
    
    /// <remarks/>
    public string FromTaxPeriod {
        get {
            return this.fromTaxPeriodField;
        }
        set {
            this.fromTaxPeriodField = value;
        }
    }
    
    /// <remarks/>
    public string ToTaxPeriod {
        get {
            return this.toTaxPeriodField;
        }
        set {
            this.toTaxPeriodField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sars.gov.za/GMD/StatusManagement/xml/schemas/version/1.14")]
public partial class TaxYearRangeStructure {
    
    private string fromTaxYearField;
    
    private string toTaxYearField;
    
    /// <remarks/>
    public string FromTaxYear {
        get {
            return this.fromTaxYearField;
        }
        set {
            this.fromTaxYearField = value;
        }
    }
    
    /// <remarks/>
    public string ToTaxYear {
        get {
            return this.toTaxYearField;
        }
        set {
            this.toTaxYearField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sars.gov.za/GMD/StatusManagement/xml/schemas/version/1.14")]
public partial class SubReferenceStructure {
    
    private SubReferenceStructureType typeField;
    
    private string valueField;
    
    /// <remarks/>
    public SubReferenceStructureType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sars.gov.za/GMD/StatusManagement/xml/schemas/version/1.14")]
public enum SubReferenceStructureType {
    
    /// <remarks/>
    FORM_ID,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sars.gov.za/enterpriseMessagingModel/GMD/BaseTypes/xml/schemas/version" +
    "/54.13")]
public enum TypeOfTaxType {
    
    /// <remarks/>
    INCOME_TAX,
    
    /// <remarks/>
    PAYE,
    
    /// <remarks/>
    VAT,
    
    /// <remarks/>
    CUSTOMS,
    
    /// <remarks/>
    EXCISE,
    
    /// <remarks/>
    UIF,
    
    /// <remarks/>
    SDL,
    
    /// <remarks/>
    DIESEL,
    
    /// <remarks/>
    PROVISIONAL_TAX,
    
    /// <remarks/>
    DIVIDENDS_TAX,
    
    /// <remarks/>
    APT,
    
    /// <remarks/>
    ASSESSED_TAX,
    
    /// <remarks/>
    ADMIN_PENALTY,
    
    /// <remarks/>
    TRANSFER_DUTY,
    
    /// <remarks/>
    CORPORATE_TAX,
    
    /// <remarks/>
    ESTATE_TAX,
    
    /// <remarks/>
    STC,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sars.gov.za/GMD/StatusManagement/xml/schemas/version/1.14")]
[System.Xml.Serialization.XmlRootAttribute("StatusManagementResponse", Namespace="http://www.sars.gov.za/GMD/StatusManagement/xml/schemas/version/1.14", IsNullable=false)]
public partial class StatusManagementResponseStructure {
    
    private CaseStatusResultStructure caseStatusResultField;
    
    private WorkflowStatusResultStructure[] workflowStatusResultsField;
    
    private ProcessStatusResultStructure[] processStatusResultsField;
    
    private FileStatusResultStructure[] fileStatusResultsField;
    
    private TypeOfTaxType taxTypeField;
    
    private string tradingNameField;
    
    /// <remarks/>
    public CaseStatusResultStructure CaseStatusResult {
        get {
            return this.caseStatusResultField;
        }
        set {
            this.caseStatusResultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("WorkflowStatusResult", IsNullable=false)]
    public WorkflowStatusResultStructure[] WorkflowStatusResults {
        get {
            return this.workflowStatusResultsField;
        }
        set {
            this.workflowStatusResultsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ProcessStatusResult", IsNullable=false)]
    public ProcessStatusResultStructure[] ProcessStatusResults {
        get {
            return this.processStatusResultsField;
        }
        set {
            this.processStatusResultsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("FileStatusResult", IsNullable=false)]
    public FileStatusResultStructure[] FileStatusResults {
        get {
            return this.fileStatusResultsField;
        }
        set {
            this.fileStatusResultsField = value;
        }
    }
    
    /// <remarks/>
    public TypeOfTaxType TaxType {
        get {
            return this.taxTypeField;
        }
        set {
            this.taxTypeField = value;
        }
    }
    
    /// <remarks/>
    public string TradingName {
        get {
            return this.tradingNameField;
        }
        set {
            this.tradingNameField = value;
        }
    }
}
