//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sars.ESBSchema.ApplicationInformation.v000002
{



    using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sars.gov.za/services/esb/v000002/applicationInformation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sars.gov.za/services/esb/v000002/applicationInformation", IsNullable = false)]
    public partial class applicationInformation
    {

        private applicationInformationApplicationInformationResult[] applicationInformationResultField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("applicationInformationResult")]
        public applicationInformationApplicationInformationResult[] applicationInformationResult
        {
            get { return this.applicationInformationResultField; }
            set { this.applicationInformationResultField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,Namespace = "http://www.sars.gov.za/services/esb/v000002/applicationInformation")]
    public partial class applicationInformationApplicationInformationResult
    {

        private MessageTypeEnum messageTypeField;

        private string applicationInformationCodeField;

        private string applicationInformationDescriptionField;

        private string applicationInformationStateField;

        /// <remarks/>
        public MessageTypeEnum MessageType
        {
            get { return this.messageTypeField; }
            set { this.messageTypeField = value; }
        }

        /// <remarks/>
        public string applicationInformationCode
        {
            get { return this.applicationInformationCodeField; }
            set { this.applicationInformationCodeField = value; }
        }

        /// <remarks/>
        public string applicationInformationDescription
        {
            get { return this.applicationInformationDescriptionField; }
            set { this.applicationInformationDescriptionField = value; }
        }

        /// <remarks/>
        public string applicationInformationState
        {
            get { return this.applicationInformationStateField; }
            set { this.applicationInformationStateField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sars.gov.za/services/esb/v000002/applicationInformation")]
    public enum MessageTypeEnum
    {

        /// <remarks/>
        Information,

        /// <remarks/>
        Warning,

        /// <remarks/>
        Error,
    }

}