//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sars.ESBSchema.ApplicationInformation.v31
{



    using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "http://www.egovernment.gov.za/GMD/ApplicationInformation/xml/schemas/version/3.1")]
    [System.Xml.Serialization.XmlRootAttribute("ApplicationInformation",
        Namespace = "http://www.egovernment.gov.za/GMD/ApplicationInformation/xml/schemas/version/3.1",
        IsNullable = false)]
    public partial class ApplicationInformationStructure
    {

        private ApplicationInformationStructureBusinessReference businessReferenceField;

        private ApplicationInformationStructureApplicationInformationResult[] applicationInformationResultField;

        /// <remarks/>
        public ApplicationInformationStructureBusinessReference BusinessReference
        {
            get { return this.businessReferenceField; }
            set { this.businessReferenceField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ApplicationInformationResult")]
        public ApplicationInformationStructureApplicationInformationResult[] ApplicationInformationResult
        {
            get { return this.applicationInformationResultField; }
            set { this.applicationInformationResultField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.egovernment.gov.za/GMD/ApplicationInformation/xml/schemas/version/3.1")]
    public partial class ApplicationInformationStructureBusinessReference
    {

        private string identifierTypeField;

        private string identifierValueField;

        /// <remarks/>
        public string IdentifierType
        {
            get { return this.identifierTypeField; }
            set { this.identifierTypeField = value; }
        }

        /// <remarks/>
        public string IdentifierValue
        {
            get { return this.identifierValueField; }
            set { this.identifierValueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.egovernment.gov.za/GMD/ApplicationInformation/xml/schemas/version/3.1")]
    public partial class ApplicationInformationStructureApplicationInformationResult
    {

        private MessageTypeEnum messageTypeField;

        private string codeField;

        private string descriptionField;

        private string referenceField;

        /// <remarks/>
        public MessageTypeEnum MessageType
        {
            get { return this.messageTypeField; }
            set { this.messageTypeField = value; }
        }

        /// <remarks/>
        public string Code
        {
            get { return this.codeField; }
            set { this.codeField = value; }
        }

        /// <remarks/>
        public string Description
        {
            get { return this.descriptionField; }
            set { this.descriptionField = value; }
        }

        /// <remarks/>
        public string Reference
        {
            get { return this.referenceField; }
            set { this.referenceField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "http://www.egovernment.gov.za/GMD/ApplicationInformation/xml/schemas/version/3.1")]
    public enum MessageTypeEnum
    {

        /// <remarks/>
        INFORMATION,

        /// <remarks/>
        WARNING,

        /// <remarks/>
        ERROR,
    }
}