//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sars.ESBSchema.ApplicationInformation
{



    using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.sars.gov.za/esb/common/v000006/header")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sars.gov.za/esb/common/v000006/header",
        IsNullable = false)]
    public partial class MessageIdentification
    {

        private string channelIDField;

        private string applicationIDField;

        private string messageSeqNoField;

        private System.DateTime messageTimeStampField;

        private string externalReferenceIDField;

        private MessageIdentificationGlobalUniqueID globalUniqueIDField;

        private string parentUniqueIDField;

        private string originalUniqueIDField;

        private string transactionTypeField;

        private long interfaceIDField;

        private bool interfaceIDFieldSpecified;

        private System.DateTime sARSReceivedTimeStampField;

        private bool sARSReceivedTimeStampFieldSpecified;

        private string externalChannelReferenceNoField;

        /// <remarks/>
        public string channelID
        {
            get { return this.channelIDField; }
            set { this.channelIDField = value; }
        }

        /// <remarks/>
        public string applicationID
        {
            get { return this.applicationIDField; }
            set { this.applicationIDField = value; }
        }

        /// <remarks/>
        public string messageSeqNo
        {
            get { return this.messageSeqNoField; }
            set { this.messageSeqNoField = value; }
        }

        /// <remarks/>
        public System.DateTime messageTimeStamp
        {
            get { return this.messageTimeStampField; }
            set { this.messageTimeStampField = value; }
        }

        /// <remarks/>
        public string externalReferenceID
        {
            get { return this.externalReferenceIDField; }
            set { this.externalReferenceIDField = value; }
        }

        /// <remarks/>
        public MessageIdentificationGlobalUniqueID globalUniqueID
        {
            get { return this.globalUniqueIDField; }
            set { this.globalUniqueIDField = value; }
        }

        /// <remarks/>
        public string parentUniqueID
        {
            get { return this.parentUniqueIDField; }
            set { this.parentUniqueIDField = value; }
        }

        /// <remarks/>
        public string originalUniqueID
        {
            get { return this.originalUniqueIDField; }
            set { this.originalUniqueIDField = value; }
        }

        /// <remarks/>
        public string transactionType
        {
            get { return this.transactionTypeField; }
            set { this.transactionTypeField = value; }
        }

        /// <remarks/>
        public long interfaceID
        {
            get { return this.interfaceIDField; }
            set { this.interfaceIDField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool interfaceIDSpecified
        {
            get { return this.interfaceIDFieldSpecified; }
            set { this.interfaceIDFieldSpecified = value; }
        }

        /// <remarks/>
        public System.DateTime SARSReceivedTimeStamp
        {
            get { return this.sARSReceivedTimeStampField; }
            set { this.sARSReceivedTimeStampField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SARSReceivedTimeStampSpecified
        {
            get { return this.sARSReceivedTimeStampFieldSpecified; }
            set { this.sARSReceivedTimeStampFieldSpecified = value; }
        }

        /// <remarks/>
        public string externalChannelReferenceNo
        {
            get { return this.externalChannelReferenceNoField; }
            set { this.externalChannelReferenceNoField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.sars.gov.za/esb/common/v000006/header")]
    public partial class MessageIdentificationGlobalUniqueID
    {

        private string originatingChannelIDField;

        private string universalUniqueIDField;

        /// <remarks/>
        public string originatingChannelID
        {
            get { return this.originatingChannelIDField; }
            set { this.originatingChannelIDField = value; }
        }

        /// <remarks/>
        public string universalUniqueID
        {
            get { return this.universalUniqueIDField; }
            set { this.universalUniqueIDField = value; }
        }
    }

}