//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sars.ESBSchema.Header.V7_1
{



    using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "http://www.egovernment.gov.za/GMD/MessageIdentification/xml/schemas/version/7.1")]
    [System.Xml.Serialization.XmlRootAttribute("MessageIdentification",
        Namespace = "http://www.egovernment.gov.za/GMD/MessageIdentification/xml/schemas/version/7.1",
        IsNullable = false)]
    public partial class MessageIdentificationStructure
    {

        private string channelIDField;

        private string applicationIDField;

        private string messageSeqNoField;

        private System.DateTime messageTimeStampField;

        private string externalReferenceIDField;

        private string originatingChannelIDField;

        private string universalUniqueIDField;

        private string externalChannelReferenceNoField;

        private float versionNoField;

        private int priorityField;

        private string domainField;

        private string activityNameField;

        private decimal financialValue1Field;

        private bool financialValue1FieldSpecified;

        private decimal financialValue2Field;

        private bool financialValue2FieldSpecified;

        private decimal financialValue3Field;

        private bool financialValue3FieldSpecified;

        private decimal financialValue4Field;

        private bool financialValue4FieldSpecified;

        private decimal financialValue5Field;

        private bool financialValue5FieldSpecified;

        /// <remarks/>
        public string channelID
        {
            get { return this.channelIDField; }
            set { this.channelIDField = value; }
        }

        /// <remarks/>
        public string applicationID
        {
            get { return this.applicationIDField; }
            set { this.applicationIDField = value; }
        }

        /// <remarks/>
        public string messageSeqNo
        {
            get { return this.messageSeqNoField; }
            set { this.messageSeqNoField = value; }
        }

        /// <remarks/>
        public System.DateTime messageTimeStamp
        {
            get { return this.messageTimeStampField; }
            set { this.messageTimeStampField = value; }
        }

        /// <remarks/>
        public string externalReferenceID
        {
            get { return this.externalReferenceIDField; }
            set { this.externalReferenceIDField = value; }
        }

        /// <remarks/>
        public string originatingChannelID
        {
            get { return this.originatingChannelIDField; }
            set { this.originatingChannelIDField = value; }
        }

        /// <remarks/>
        public string universalUniqueID
        {
            get { return this.universalUniqueIDField; }
            set { this.universalUniqueIDField = value; }
        }

        /// <remarks/>
        public string externalChannelReferenceNo
        {
            get { return this.externalChannelReferenceNoField; }
            set { this.externalChannelReferenceNoField = value; }
        }

        /// <remarks/>
        public float versionNo
        {
            get { return this.versionNoField; }
            set { this.versionNoField = value; }
        }

        /// <remarks/>
        public int priority
        {
            get { return this.priorityField; }
            set { this.priorityField = value; }
        }

        /// <remarks/>
        public string domain
        {
            get { return this.domainField; }
            set { this.domainField = value; }
        }

        /// <remarks/>
        public string activityName
        {
            get { return this.activityNameField; }
            set { this.activityNameField = value; }
        }

        /// <remarks/>
        public decimal financialValue1
        {
            get { return this.financialValue1Field; }
            set { this.financialValue1Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool financialValue1Specified
        {
            get { return this.financialValue1FieldSpecified; }
            set { this.financialValue1FieldSpecified = value; }
        }

        /// <remarks/>
        public decimal financialValue2
        {
            get { return this.financialValue2Field; }
            set { this.financialValue2Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool financialValue2Specified
        {
            get { return this.financialValue2FieldSpecified; }
            set { this.financialValue2FieldSpecified = value; }
        }

        /// <remarks/>
        public decimal financialValue3
        {
            get { return this.financialValue3Field; }
            set { this.financialValue3Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool financialValue3Specified
        {
            get { return this.financialValue3FieldSpecified; }
            set { this.financialValue3FieldSpecified = value; }
        }

        /// <remarks/>
        public decimal financialValue4
        {
            get { return this.financialValue4Field; }
            set { this.financialValue4Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool financialValue4Specified
        {
            get { return this.financialValue4FieldSpecified; }
            set { this.financialValue4FieldSpecified = value; }
        }

        /// <remarks/>
        public decimal financialValue5
        {
            get { return this.financialValue5Field; }
            set { this.financialValue5Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool financialValue5Specified
        {
            get { return this.financialValue5FieldSpecified; }
            set { this.financialValue5FieldSpecified = value; }
        }
    }
}