//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sars.ESBSchema.Letters.SysGen
{
    using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sars.gov.za/forms/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sars.gov.za/forms/", IsNullable = false)]
    public partial class SARS_SYSGENLTR
    {

        private FORM_INFORMATION fORM_INFORMATIONField;

        private SECURITY_INFO sECURITY_INFOField;

        private SARS_SYSGENLTRTAX_TYPE tAX_TYPEField;

        private SARS_SYSGENLTRLETTERID lETTERIDField;

        private SARS_SYSGENLTRLETTER_HEADER lETTER_HEADERField;

        private string notesField;

        private SARS_SYSGENLTRADDRESSEE_DETAILS aDDRESSEE_DETAILSField;

        private SARS_SYSGENLTRCONTACT_DETAILS cONTACT_DETAILSField;

        private SARS_SYSGENLTRDETAILS dETAILSField;

        private SARS_SYSGENLTRLETTER_NAME_HEADER lETTER_NAME_HEADERField;

        private SARS_SYSGENLTRLETTER_CONTENT lETTER_CONTENTField;

        private SARS_SYSGENLTRTable[] tablesField;

        private SARS_SYSGENLTRLETTER_APPENDIX lETTER_APPENDIXField;

        private string[] paragraphsField;

        /// <remarks/>
        public FORM_INFORMATION FORM_INFORMATION
        {
            get { return this.fORM_INFORMATIONField; }
            set { this.fORM_INFORMATIONField = value; }
        }

        /// <remarks/>
        public SECURITY_INFO SECURITY_INFO
        {
            get { return this.sECURITY_INFOField; }
            set { this.sECURITY_INFOField = value; }
        }

        /// <remarks/>
        public SARS_SYSGENLTRTAX_TYPE TAX_TYPE
        {
            get { return this.tAX_TYPEField; }
            set { this.tAX_TYPEField = value; }
        }

        /// <remarks/>
        public SARS_SYSGENLTRLETTERID LETTERID
        {
            get { return this.lETTERIDField; }
            set { this.lETTERIDField = value; }
        }

        /// <remarks/>
        public SARS_SYSGENLTRLETTER_HEADER LETTER_HEADER
        {
            get { return this.lETTER_HEADERField; }
            set { this.lETTER_HEADERField = value; }
        }

        /// <remarks/>
        public string Notes
        {
            get { return this.notesField; }
            set { this.notesField = value; }
        }

        /// <remarks/>
        public SARS_SYSGENLTRADDRESSEE_DETAILS ADDRESSEE_DETAILS
        {
            get { return this.aDDRESSEE_DETAILSField; }
            set { this.aDDRESSEE_DETAILSField = value; }
        }

        /// <remarks/>
        public SARS_SYSGENLTRCONTACT_DETAILS CONTACT_DETAILS
        {
            get { return this.cONTACT_DETAILSField; }
            set { this.cONTACT_DETAILSField = value; }
        }

        /// <remarks/>
        public SARS_SYSGENLTRDETAILS DETAILS
        {
            get { return this.dETAILSField; }
            set { this.dETAILSField = value; }
        }

        /// <remarks/>
        public SARS_SYSGENLTRLETTER_NAME_HEADER LETTER_NAME_HEADER
        {
            get { return this.lETTER_NAME_HEADERField; }
            set { this.lETTER_NAME_HEADERField = value; }
        }

        /// <remarks/>
        public SARS_SYSGENLTRLETTER_CONTENT LETTER_CONTENT
        {
            get { return this.lETTER_CONTENTField; }
            set { this.lETTER_CONTENTField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Table", IsNullable = false)]
        public SARS_SYSGENLTRTable[] Tables
        {
            get { return this.tablesField; }
            set { this.tablesField = value; }
        }

        /// <remarks/>
        public SARS_SYSGENLTRLETTER_APPENDIX LETTER_APPENDIX
        {
            get { return this.lETTER_APPENDIXField; }
            set { this.lETTER_APPENDIXField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Paragraph", IsNullable = false)]
        public string[] Paragraphs
        {
            get { return this.paragraphsField; }
            set { this.paragraphsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sars.gov.za/forms/")]
    public partial class FORM_INFORMATION
    {

        private string fORM_IDField;

        private GlobalUniqueIDStructure gUIDField;

        private System.DateTime tIMESTAMPField;

        private bool tIMESTAMPFieldSpecified;

        private string vERSION_NOField;

        private string hAS_SUPPORT_DOCSField;

        private string sIGNEDField;

        private string iNCOMPLETEField;

        private string tAX_YEARField;

        private string fORM_YEARField;

        private string tAX_REF_NOField;

        private string lANGUAGEField;

        private string aREA_CODEField;

        private string sOURCE_IDField;

        private string sUBMIT_URLField;

        private string sAVE_URLField;

        private string sAVE_URL_WSField;

        private string fORM_TYPEField;

        private string rEVISION_NOField;

        private string iT_IDField;

        private string wIZARD_IDField;

        private string uSER_RIGHTSField;

        private string iS_ONLINEField;

        private string uNIQUEREFField;

        private string rEAD_ONLYField;

        private META_DATADATA[] mETA_DATAField;

        private string cURR_CALENDAR_YEARField;

        private string dATE_RECEIVEDField;

        private string hASHField;

        private SIGNATURE_BIO sIGNATURE_BIOField;

        private string sCANNING_VERSIONField;

        private string pARTY_NUMBERField;

        private string cASE_NUMBERField;

        private string tRANSACTION_DATEField;

        private FORM_INFORMATIONPRINT_INDICATOR pRINT_INDICATORField;

        private bool pRINT_INDICATORFieldSpecified;

        private string cALCULATE_URLField;

        /// <remarks/>
        public string FORM_ID
        {
            get { return this.fORM_IDField; }
            set { this.fORM_IDField = value; }
        }

        /// <remarks/>
        public GlobalUniqueIDStructure GUID
        {
            get { return this.gUIDField; }
            set { this.gUIDField = value; }
        }

        /// <remarks/>
        public System.DateTime TIMESTAMP
        {
            get { return this.tIMESTAMPField; }
            set { this.tIMESTAMPField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TIMESTAMPSpecified
        {
            get { return this.tIMESTAMPFieldSpecified; }
            set { this.tIMESTAMPFieldSpecified = value; }
        }

        /// <remarks/>
        public string VERSION_NO
        {
            get { return this.vERSION_NOField; }
            set { this.vERSION_NOField = value; }
        }

        /// <remarks/>
        public string HAS_SUPPORT_DOCS
        {
            get { return this.hAS_SUPPORT_DOCSField; }
            set { this.hAS_SUPPORT_DOCSField = value; }
        }

        /// <remarks/>
        public string SIGNED
        {
            get { return this.sIGNEDField; }
            set { this.sIGNEDField = value; }
        }

        /// <remarks/>
        public string INCOMPLETE
        {
            get { return this.iNCOMPLETEField; }
            set { this.iNCOMPLETEField = value; }
        }

        /// <remarks/>
        public string TAX_YEAR
        {
            get { return this.tAX_YEARField; }
            set { this.tAX_YEARField = value; }
        }

        /// <remarks/>
        public string FORM_YEAR
        {
            get { return this.fORM_YEARField; }
            set { this.fORM_YEARField = value; }
        }

        /// <remarks/>
        public string TAX_REF_NO
        {
            get { return this.tAX_REF_NOField; }
            set { this.tAX_REF_NOField = value; }
        }

        /// <remarks/>
        public string LANGUAGE
        {
            get { return this.lANGUAGEField; }
            set { this.lANGUAGEField = value; }
        }

        /// <remarks/>
        public string AREA_CODE
        {
            get { return this.aREA_CODEField; }
            set { this.aREA_CODEField = value; }
        }

        /// <remarks/>
        public string SOURCE_ID
        {
            get { return this.sOURCE_IDField; }
            set { this.sOURCE_IDField = value; }
        }

        /// <remarks/>
        public string SUBMIT_URL
        {
            get { return this.sUBMIT_URLField; }
            set { this.sUBMIT_URLField = value; }
        }

        /// <remarks/>
        public string SAVE_URL
        {
            get { return this.sAVE_URLField; }
            set { this.sAVE_URLField = value; }
        }

        /// <remarks/>
        public string SAVE_URL_WS
        {
            get { return this.sAVE_URL_WSField; }
            set { this.sAVE_URL_WSField = value; }
        }

        /// <remarks/>
        public string FORM_TYPE
        {
            get { return this.fORM_TYPEField; }
            set { this.fORM_TYPEField = value; }
        }

        /// <remarks/>
        public string REVISION_NO
        {
            get { return this.rEVISION_NOField; }
            set { this.rEVISION_NOField = value; }
        }

        /// <remarks/>
        public string IT_ID
        {
            get { return this.iT_IDField; }
            set { this.iT_IDField = value; }
        }

        /// <remarks/>
        public string WIZARD_ID
        {
            get { return this.wIZARD_IDField; }
            set { this.wIZARD_IDField = value; }
        }

        /// <remarks/>
        public string USER_RIGHTS
        {
            get { return this.uSER_RIGHTSField; }
            set { this.uSER_RIGHTSField = value; }
        }

        /// <remarks/>
        public string IS_ONLINE
        {
            get { return this.iS_ONLINEField; }
            set { this.iS_ONLINEField = value; }
        }

        /// <remarks/>
        public string UNIQUEREF
        {
            get { return this.uNIQUEREFField; }
            set { this.uNIQUEREFField = value; }
        }

        /// <remarks/>
        public string READ_ONLY
        {
            get { return this.rEAD_ONLYField; }
            set { this.rEAD_ONLYField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DATA", IsNullable = false)]
        public META_DATADATA[] META_DATA
        {
            get { return this.mETA_DATAField; }
            set { this.mETA_DATAField = value; }
        }

        /// <remarks/>
        public string CURR_CALENDAR_YEAR
        {
            get { return this.cURR_CALENDAR_YEARField; }
            set { this.cURR_CALENDAR_YEARField = value; }
        }

        /// <remarks/>
        public string DATE_RECEIVED
        {
            get { return this.dATE_RECEIVEDField; }
            set { this.dATE_RECEIVEDField = value; }
        }

        /// <remarks/>
        public string HASH
        {
            get { return this.hASHField; }
            set { this.hASHField = value; }
        }

        /// <remarks/>
        public SIGNATURE_BIO SIGNATURE_BIO
        {
            get { return this.sIGNATURE_BIOField; }
            set { this.sIGNATURE_BIOField = value; }
        }

        /// <remarks/>
        public string SCANNING_VERSION
        {
            get { return this.sCANNING_VERSIONField; }
            set { this.sCANNING_VERSIONField = value; }
        }

        /// <remarks/>
        public string PARTY_NUMBER
        {
            get { return this.pARTY_NUMBERField; }
            set { this.pARTY_NUMBERField = value; }
        }

        /// <remarks/>
        public string CASE_NUMBER
        {
            get { return this.cASE_NUMBERField; }
            set { this.cASE_NUMBERField = value; }
        }

        /// <remarks/>
        public string TRANSACTION_DATE
        {
            get { return this.tRANSACTION_DATEField; }
            set { this.tRANSACTION_DATEField = value; }
        }

        /// <remarks/>
        public FORM_INFORMATIONPRINT_INDICATOR PRINT_INDICATOR
        {
            get { return this.pRINT_INDICATORField; }
            set { this.pRINT_INDICATORField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PRINT_INDICATORSpecified
        {
            get { return this.pRINT_INDICATORFieldSpecified; }
            set { this.pRINT_INDICATORFieldSpecified = value; }
        }

        /// <remarks/>
        public string CALCULATE_URL
        {
            get { return this.cALCULATE_URLField; }
            set { this.cALCULATE_URLField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sars.gov.za/forms/")]
    public partial class GlobalUniqueIDStructure
    {

        private string uniqueIdentifierField;

        private ChannelIDType originatingChannelIDField;

        /// <remarks/>
        public string UniqueIdentifier
        {
            get { return this.uniqueIdentifierField; }
            set { this.uniqueIdentifierField = value; }
        }

        /// <remarks/>
        public ChannelIDType OriginatingChannelID
        {
            get { return this.originatingChannelIDField; }
            set { this.originatingChannelIDField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sars.gov.za/forms/")]
    public enum ChannelIDType
    {

        /// <remarks/>
        ATP,

        /// <remarks/>
        SMA,

        /// <remarks/>
        SCN,

        /// <remarks/>
        CTV,

        /// <remarks/>
        CTV_ALB,

        /// <remarks/>
        CTV_BEL,

        /// <remarks/>
        CTV_DRK,

        /// <remarks/>
        CTV_DBN,

        /// <remarks/>
        CTV_BRO,

        /// <remarks/>
        ITS,

        /// <remarks/>
        OPV,

        /// <remarks/>
        EFL,

        /// <remarks/>
        IFL,

        /// <remarks/>
        U3TM,

        /// <remarks/>
        BLK,

        /// <remarks/>
        LTT,

        /// <remarks/>
        DCTM,

        /// <remarks/>
        DCTM_ALB,

        /// <remarks/>
        DCTM_BEL,

        /// <remarks/>
        DCTM_DRK,

        /// <remarks/>
        DCTM_DBN,

        /// <remarks/>
        DCTM_BRO,

        /// <remarks/>
        CRP,

        /// <remarks/>
        IVR,

        /// <remarks/>
        SAP,

        /// <remarks/>
        ESB,

        /// <remarks/>
        EDI,

        /// <remarks/>
        XML,

        /// <remarks/>
        TTS,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sars.gov.za/forms/")]
    public partial class SECURITY_INFO
    {

        private string sESSIONIDField;

        private string tAXUSERIDField;

        private string tAXPAYERIDField;

        private string rETURNGROUPIDField;

        /// <remarks/>
        public string SESSIONID
        {
            get { return this.sESSIONIDField; }
            set { this.sESSIONIDField = value; }
        }

        /// <remarks/>
        public string TAXUSERID
        {
            get { return this.tAXUSERIDField; }
            set { this.tAXUSERIDField = value; }
        }

        /// <remarks/>
        public string TAXPAYERID
        {
            get { return this.tAXPAYERIDField; }
            set { this.tAXPAYERIDField = value; }
        }

        /// <remarks/>
        public string RETURNGROUPID
        {
            get { return this.rETURNGROUPIDField; }
            set { this.rETURNGROUPIDField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sars.gov.za/forms/")]
    public partial class SIGNATURE_BIO
    {

        private string[] sIGNATUREField;

        private string[] iMAGEField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SIGNATURE")]
        public string[] SIGNATURE
        {
            get { return this.sIGNATUREField; }
            set { this.sIGNATUREField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IMAGE")]
        public string[] IMAGE
        {
            get { return this.iMAGEField; }
            set { this.iMAGEField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sars.gov.za/forms/")]
    public partial class META_DATADATA
    {

        private string nAMEField;

        private string vALUEField;

        /// <remarks/>
        public string NAME
        {
            get { return this.nAMEField; }
            set { this.nAMEField = value; }
        }

        /// <remarks/>
        public string VALUE
        {
            get { return this.vALUEField; }
            set { this.vALUEField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sars.gov.za/forms/")]
    public enum FORM_INFORMATIONPRINT_INDICATOR
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")] Item,

        /// <remarks/>
        SARS,

        /// <remarks/>
        TAXPAYER,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sars.gov.za/forms/")]
    public partial class SARS_SYSGENLTRTAX_TYPE
    {

        private string tAX_TYPE_LABELField;

        /// <remarks/>
        public string TAX_TYPE_LABEL
        {
            get { return this.tAX_TYPE_LABELField; }
            set { this.tAX_TYPE_LABELField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sars.gov.za/forms/")]
    public partial class SARS_SYSGENLTRLETTERID
    {

        private string lETTERID_LABELField;

        /// <remarks/>
        public string LETTERID_LABEL
        {
            get { return this.lETTERID_LABELField; }
            set { this.lETTERID_LABELField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sars.gov.za/forms/")]
    public partial class SARS_SYSGENLTRLETTER_HEADER
    {

        private string lETTER_HEADER_LABELField;

        /// <remarks/>
        public string LETTER_HEADER_LABEL
        {
            get { return this.lETTER_HEADER_LABELField; }
            set { this.lETTER_HEADER_LABELField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sars.gov.za/forms/")]
    public partial class SARS_SYSGENLTRADDRESSEE_DETAILS
    {

        private string aDDRESS_FIELD_F001Field;

        private string aDDRESS_FIELD_F002Field;

        private string aDDRESS_FIELD_F003Field;

        private string aDDRESS_FIELD_F004Field;

        private string aDDRESS_FIELD_F005Field;

        private string aDDRESS_FIELD_F006Field;

        private string aDDRESS_FIELD_F007Field;

        /// <remarks/>
        public string ADDRESS_FIELD_F001
        {
            get { return this.aDDRESS_FIELD_F001Field; }
            set { this.aDDRESS_FIELD_F001Field = value; }
        }

        /// <remarks/>
        public string ADDRESS_FIELD_F002
        {
            get { return this.aDDRESS_FIELD_F002Field; }
            set { this.aDDRESS_FIELD_F002Field = value; }
        }

        /// <remarks/>
        public string ADDRESS_FIELD_F003
        {
            get { return this.aDDRESS_FIELD_F003Field; }
            set { this.aDDRESS_FIELD_F003Field = value; }
        }

        /// <remarks/>
        public string ADDRESS_FIELD_F004
        {
            get { return this.aDDRESS_FIELD_F004Field; }
            set { this.aDDRESS_FIELD_F004Field = value; }
        }

        /// <remarks/>
        public string ADDRESS_FIELD_F005
        {
            get { return this.aDDRESS_FIELD_F005Field; }
            set { this.aDDRESS_FIELD_F005Field = value; }
        }

        /// <remarks/>
        public string ADDRESS_FIELD_F006
        {
            get { return this.aDDRESS_FIELD_F006Field; }
            set { this.aDDRESS_FIELD_F006Field = value; }
        }

        /// <remarks/>
        public string ADDRESS_FIELD_F007
        {
            get { return this.aDDRESS_FIELD_F007Field; }
            set { this.aDDRESS_FIELD_F007Field = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sars.gov.za/forms/")]
    public partial class SARS_SYSGENLTRCONTACT_DETAILS
    {

        private string headerLabelField;

        private string aDDRESS_CD01Field;

        private string tEL_NO_CD02Field;

        private string wEB_ADDRESS_CD03Field;

        private string tOLL_FREE_NO_CD04Field;

        private string fAX_NO_CD05Field;

        private string eMAIL_ADDRESS_CD06Field;

        /// <remarks/>
        public string HeaderLabel
        {
            get { return this.headerLabelField; }
            set { this.headerLabelField = value; }
        }

        /// <remarks/>
        public string ADDRESS_CD01
        {
            get { return this.aDDRESS_CD01Field; }
            set { this.aDDRESS_CD01Field = value; }
        }

        /// <remarks/>
        public string TEL_NO_CD02
        {
            get { return this.tEL_NO_CD02Field; }
            set { this.tEL_NO_CD02Field = value; }
        }

        /// <remarks/>
        public string WEB_ADDRESS_CD03
        {
            get { return this.wEB_ADDRESS_CD03Field; }
            set { this.wEB_ADDRESS_CD03Field = value; }
        }

        /// <remarks/>
        public string TOLL_FREE_NO_CD04
        {
            get { return this.tOLL_FREE_NO_CD04Field; }
            set { this.tOLL_FREE_NO_CD04Field = value; }
        }

        /// <remarks/>
        public string FAX_NO_CD05
        {
            get { return this.fAX_NO_CD05Field; }
            set { this.fAX_NO_CD05Field = value; }
        }

        /// <remarks/>
        public string EMAIL_ADDRESS_CD06
        {
            get { return this.eMAIL_ADDRESS_CD06Field; }
            set { this.eMAIL_ADDRESS_CD06Field = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sars.gov.za/forms/")]
    public partial class SARS_SYSGENLTRDETAILS
    {

        private string headerLabelField;

        private SARS_SYSGENLTRDETAILSCASE_NO cASE_NOField;

        private SARS_SYSGENLTRDETAILSTAXREF_NO tAXREF_NOField;

        private SARS_SYSGENLTRDETAILSENQUIRY_NOTE eNQUIRY_NOTEField;

        private SARS_SYSGENLTRDETAILSDATE dATEField;

        private SARS_SYSGENLTRDETAILSFromDate fromDateField;

        private SARS_SYSGENLTRDETAILSToDate toDateField;

        private SARS_SYSGENLTRDETAILSTransactionNo transactionNoField;

        private SARS_SYSGENLTRDETAILSClientReferenceNo clientReferenceNoField;

        /// <remarks/>
        public string HeaderLabel
        {
            get { return this.headerLabelField; }
            set { this.headerLabelField = value; }
        }

        /// <remarks/>
        public SARS_SYSGENLTRDETAILSCASE_NO CASE_NO
        {
            get { return this.cASE_NOField; }
            set { this.cASE_NOField = value; }
        }

        /// <remarks/>
        public SARS_SYSGENLTRDETAILSTAXREF_NO TAXREF_NO
        {
            get { return this.tAXREF_NOField; }
            set { this.tAXREF_NOField = value; }
        }

        /// <remarks/>
        public SARS_SYSGENLTRDETAILSENQUIRY_NOTE ENQUIRY_NOTE
        {
            get { return this.eNQUIRY_NOTEField; }
            set { this.eNQUIRY_NOTEField = value; }
        }

        /// <remarks/>
        public SARS_SYSGENLTRDETAILSDATE DATE
        {
            get { return this.dATEField; }
            set { this.dATEField = value; }
        }

        /// <remarks/>
        public SARS_SYSGENLTRDETAILSFromDate FromDate
        {
            get { return this.fromDateField; }
            set { this.fromDateField = value; }
        }

        /// <remarks/>
        public SARS_SYSGENLTRDETAILSToDate ToDate
        {
            get { return this.toDateField; }
            set { this.toDateField = value; }
        }

        /// <remarks/>
        public SARS_SYSGENLTRDETAILSTransactionNo TransactionNo
        {
            get { return this.transactionNoField; }
            set { this.transactionNoField = value; }
        }

        /// <remarks/>
        public SARS_SYSGENLTRDETAILSClientReferenceNo ClientReferenceNo
        {
            get { return this.clientReferenceNoField; }
            set { this.clientReferenceNoField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sars.gov.za/forms/")]
    public partial class SARS_SYSGENLTRDETAILSCASE_NO
    {

        private string cASE_LABEL_L001Field;

        private string cASE_FIELD_F002Field;

        /// <remarks/>
        public string CASE_LABEL_L001
        {
            get { return this.cASE_LABEL_L001Field; }
            set { this.cASE_LABEL_L001Field = value; }
        }

        /// <remarks/>
        public string CASE_FIELD_F002
        {
            get { return this.cASE_FIELD_F002Field; }
            set { this.cASE_FIELD_F002Field = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sars.gov.za/forms/")]
    public partial class SARS_SYSGENLTRDETAILSTAXREF_NO
    {

        private string tAXREF_LABEL_L003Field;

        private string tAXREF_FIELD_F004Field;

        /// <remarks/>
        public string TAXREF_LABEL_L003
        {
            get { return this.tAXREF_LABEL_L003Field; }
            set { this.tAXREF_LABEL_L003Field = value; }
        }

        /// <remarks/>
        public string TAXREF_FIELD_F004
        {
            get { return this.tAXREF_FIELD_F004Field; }
            set { this.tAXREF_FIELD_F004Field = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sars.gov.za/forms/")]
    public partial class SARS_SYSGENLTRDETAILSENQUIRY_NOTE
    {

        private string nOTE_LABEL_L005Field;

        /// <remarks/>
        public string NOTE_LABEL_L005
        {
            get { return this.nOTE_LABEL_L005Field; }
            set { this.nOTE_LABEL_L005Field = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sars.gov.za/forms/")]
    public partial class SARS_SYSGENLTRDETAILSDATE
    {

        private string dATE_LABEL_L008Field;

        private string dATE_FIELD_F009Field;

        /// <remarks/>
        public string DATE_LABEL_L008
        {
            get { return this.dATE_LABEL_L008Field; }
            set { this.dATE_LABEL_L008Field = value; }
        }

        /// <remarks/>
        public string DATE_FIELD_F009
        {
            get { return this.dATE_FIELD_F009Field; }
            set { this.dATE_FIELD_F009Field = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sars.gov.za/forms/")]
    public partial class SARS_SYSGENLTRDETAILSFromDate
    {

        private string fromDateLabelField;

        private System.DateTime fromDateValueField;

        /// <remarks/>
        public string FromDateLabel
        {
            get { return this.fromDateLabelField; }
            set { this.fromDateLabelField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime FromDateValue
        {
            get { return this.fromDateValueField; }
            set { this.fromDateValueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sars.gov.za/forms/")]
    public partial class SARS_SYSGENLTRDETAILSToDate
    {

        private string toDateLabelField;

        private System.DateTime toDateValueField;

        /// <remarks/>
        public string ToDateLabel
        {
            get { return this.toDateLabelField; }
            set { this.toDateLabelField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime ToDateValue
        {
            get { return this.toDateValueField; }
            set { this.toDateValueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sars.gov.za/forms/")]
    public partial class SARS_SYSGENLTRDETAILSTransactionNo
    {

        private string transactionNoLabelField;

        private string transactionNoValueField;

        /// <remarks/>
        public string TransactionNoLabel
        {
            get { return this.transactionNoLabelField; }
            set { this.transactionNoLabelField = value; }
        }

        /// <remarks/>
        public string TransactionNoValue
        {
            get { return this.transactionNoValueField; }
            set { this.transactionNoValueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sars.gov.za/forms/")]
    public partial class SARS_SYSGENLTRDETAILSClientReferenceNo
    {

        private string clientReferenceNoLabelField;

        private string clientReferenceNoValueField;

        /// <remarks/>
        public string ClientReferenceNoLabel
        {
            get { return this.clientReferenceNoLabelField; }
            set { this.clientReferenceNoLabelField = value; }
        }

        /// <remarks/>
        public string ClientReferenceNoValue
        {
            get { return this.clientReferenceNoValueField; }
            set { this.clientReferenceNoValueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sars.gov.za/forms/")]
    public partial class SARS_SYSGENLTRLETTER_NAME_HEADER
    {

        private string lETTER_NAMEField;

        /// <remarks/>
        public string LETTER_NAME
        {
            get { return this.lETTER_NAMEField; }
            set { this.lETTER_NAMEField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sars.gov.za/forms/")]
    public partial class SARS_SYSGENLTRLETTER_CONTENT
    {

        private string cONTENTField;

        /// <remarks/>
        public string CONTENT
        {
            get { return this.cONTENTField; }
            set { this.cONTENTField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sars.gov.za/forms/")]
    public partial class SARS_SYSGENLTRTable
    {

        private string descriptionField;

        private string[] headerField;

        private SARS_SYSGENLTRTableRow[] rowsField;

        private int noOfColumnsField;

        private string columnWidthField;

        /// <remarks/>
        public string Description
        {
            get { return this.descriptionField; }
            set { this.descriptionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable = false)]
        public string[] Header
        {
            get { return this.headerField; }
            set { this.headerField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Row", IsNullable = false)]
        public SARS_SYSGENLTRTableRow[] Rows
        {
            get { return this.rowsField; }
            set { this.rowsField = value; }
        }

        /// <remarks/>
        public int NoOfColumns
        {
            get { return this.noOfColumnsField; }
            set { this.noOfColumnsField = value; }
        }

        /// <remarks/>
        public string ColumnWidth
        {
            get { return this.columnWidthField; }
            set { this.columnWidthField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sars.gov.za/forms/")]
    public partial class SARS_SYSGENLTRTableRow
    {

        private string[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable = false)]
        public string[] Items
        {
            get { return this.itemsField; }
            set { this.itemsField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sars.gov.za/forms/")]
    public partial class SARS_SYSGENLTRLETTER_APPENDIX
    {

        private string aPPENDIXField;

        /// <remarks/>
        public string APPENDIX
        {
            get { return this.aPPENDIXField; }
            set { this.aPPENDIXField = value; }
        }
    }
}