USE [SARSeFiling]
GO

/****** Object:  Table [dbo].[TPDirectiveAD]    Script Date: 2016/11/09 11:08:56 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TPDirectiveAD](
	[FORMADID] [int] IDENTITY(1,1) NOT NULL,
	[DirectiveRequestID] [decimal](18, 0) NOT NULL,
	[TaxUserID] [decimal](10, 0) NOT NULL,
	[TaxPayerID] [decimal](10, 0) NOT NULL,
	[DirectiveTypeCode] [char](8) NOT NULL,
	[DirectiveGroupID] [decimal](18, 0) NOT NULL,
	[DirectiveSystemStatus] [char](5) NOT NULL,
	[BusinessProcessExecutionNum] [int] NOT NULL,
	[CompleteDt] [datetime] NULL,
	[SubmitDt] [datetime] NULL,
	[PeriodYear] [int] NOT NULL,
	[PeriodNum] [tinyint] NOT NULL,
	[DirectiveApplicationID] [varchar](50) NULL,
	[PaperRespInd] [tinyint] NULL,
	[YearOfAssesmentDt] [datetime] NULL,
	[IncomeTaxReferenceNum] [varchar](25) NULL,
	[NoIncomeTaxCode] [char](2) NULL,
	[NoIncomeTaxText] [varchar](65) NULL,
	[AnnualIncomeAmt] [money] NULL,
	[EmployeeNum] [varchar](15) NULL,
	[PersonTitleCode] [char](8) NULL,
	[Initials] [varchar](15) NULL,
	[Surname] [varchar](120) NULL,
	[FirstName] [varchar](50) NULL,
	[DateOfBirth] [datetime] NULL,
	[IDNumber] [varchar](25) NULL,
	[IDNumberOther] [varchar](25) NULL,
	[PhysicalAddress1] [varchar](50) NULL,
	[PhysicalAddress2] [varchar](50) NULL,
	[PhysicalAddress3] [varchar](50) NULL,
	[PhysicalAddress4] [varchar](50) NULL,
	[PhysicalPostCode] [varchar](50) NULL,
	[PostalAddress1] [varchar](50) NULL,
	[PostalAddress2] [varchar](50) NOT NULL,
	[PostalAddress3] [varchar](50) NULL,
	[PostalAddress4] [varchar](50) NULL,
	[PostalPostCode] [varchar](50) NULL,
	[TelAreaCode] [varchar](10) NULL,
	[TelNumber] [varchar](15) NULL,
	[FundName] [varchar](120) NULL,
	[FundNumber] [varchar](25) NULL,
	[FundContactPersonTitleCode] [char](8) NULL,
	[FundContactPersonInitials] [varchar](15) NULL,
	[FundContactPersonFirstName] [varchar](50) NULL,
	[FundContactPersonSurname] [varchar](50) NULL,
	[FundTelAreaCode] [varchar](10) NULL,
	[FundTelNumber] [varchar](15) NULL,
	[FundPostalAddress1] [varchar](50) NULL,
	[FundPostalAddress2] [varchar](50) NULL,
	[FundPostalAddress3] [varchar](50) NULL,
	[FundPostalAddress4] [varchar](50) NULL,
	[FundPostalPostCode] [varchar](50) NULL,
	[MembershipNum] [varchar](15) NULL,
	[MembershipDt] [datetime] NULL,
	[FundTypeCode] [char](2) NULL,
	[FundCreateReasonCode] [char](2) NULL,
	[GrossLumpAmt] [money] NULL,
	[ReasonForDirectiveCode] [char](2) NULL,
	[AccrualDt] [datetime] NULL,
	[TotalContributionAmt] [money] NULL,
	[ExcessContributionAmt] [money] NULL,
	[CalculationMethodCode] [char](2) NULL,
	[CalculationYearFromDt] [datetime] NULL,
	[CalculationYearToDt] [datetime] NULL,
	[CalculationCompletedYears] [int] NULL,
	[SalariesEnteredNum] [int] NULL,
	[Salary1StartDt] [datetime] NULL,
	[Salary1EndDt] [datetime] NULL,
	[Salary1Amt] [money] NULL,
	[Salary2StartDt] [datetime] NULL,
	[Salary2EndDt] [datetime] NULL,
	[Salary2Amt] [money] NULL,
	[Salary3StartDt] [datetime] NULL,
	[Salary3EndDt] [datetime] NULL,
	[Salary3Amt] [money] NULL,
	[Salary4StartDt] [datetime] NULL,
	[Salary4EndDt] [datetime] NULL,
	[Salary4Amt] [money] NULL,
	[Salary5StartDt] [datetime] NULL,
	[Salary5EndDt] [datetime] NULL,
	[Salary5Amt] [money] NULL,
	[SalaryTotalAmt] [money] NULL,
	[SalaryAverageAmt] [money] NULL,
	[Salary12MonthPreDeathAmt] [money] NULL,
	[EmployerName] [varchar](120) NULL,
	[EmployerPAYENum] [varchar](25) NULL,
	[EmployerContactPersonTitleCode] [char](8) NULL,
	[EmployerContactPersonInitials] [varchar](15) NULL,
	[EmployerContactPersonFirstName] [varchar](50) NULL,
	[EmployerContactPersonSurname] [varchar](50) NULL,
	[EmployerTelAreaCode] [varchar](10) NULL,
	[EmployerTelNumber] [varchar](15) NULL,
	[EmployerPhysicalAddress1] [varchar](50) NULL,
	[EmployerPhysicalAddress2] [varchar](50) NULL,
	[EmployerPhysicalAddress3] [varchar](50) NULL,
	[EmployerPhysicalAddress4] [varchar](50) NULL,
	[EmployerPhysicalPostCode] [varchar](50) NULL,
	[EmployerPostalAddress1] [varchar](50) NULL,
	[EmployerPostalAddress2] [varchar](50) NULL,
	[EmployerPostalAddress3] [varchar](50) NULL,
	[EmployerPostalAddress4] [varchar](50) NULL,
	[EmployerPostalPostCode] [varchar](50) NULL,
	[ITArea] [char](4) NULL,
	[DirectiveStatusCode] [char](2) NULL,
	[IssueDt] [datetime] NULL,
	[ValidStartDt] [datetime] NULL,
	[ValidEndDt] [datetime] NULL,
	[TaxFreePortionAmt] [money] NULL,
	[GrossPayablePAYEAmt] [money] NULL,
	[DeductionFrequency] [char](1) NULL,
	[AllowedContributionAmt] [money] NULL,
	[SOIT88LRefNum] [varchar](25) NULL,
	[SOAssessedTaxAmt] [money] NULL,
	[SOProvisionalTax1Amt] [money] NULL,
	[SOProvisionalTax1Period] [char](6) NULL,
	[SOProvisionalTax2Amt] [money] NULL,
	[SOProvisionalTax2Period] [char](6) NULL,
	[SOProvisionalTax3Amt] [money] NULL,
	[SOProvisionalTax3Period] [char](6) NULL,
	[SOVATNum] [varchar](25) NULL,
	[SOVATAmt] [money] NULL,
	[SOPAYENum] [varchar](25) NULL,
	[SOPAYEAmt] [money] NULL,
	[Comment] [varchar](255) NULL,
	[SARSIncomeTaxReferenceNum] [varchar](25) NULL,
	[DirectiveCancelCode] [char](2) NULL,
	[DirectiveID] [decimal](18, 0) NULL,
	[FundPAYENum] [varchar](25) NULL,
	[GrossTotalBenefitAmt] [money] NULL CONSTRAINT [DF_TPDirectiveAD_GrossTotalBenefitAmt]  DEFAULT (0),
	[DivorceSpouseAmt] [money] NULL CONSTRAINT [DF_TPDirectiveAD_DivorceSpouseAmt]  DEFAULT (0),
	[BenefitCalcInd] [tinyint] NULL CONSTRAINT [DF_TPDirectiveAD_BenefitCalcInd]  DEFAULT (0),
	[FundAnnuityInd] [tinyint] NULL CONSTRAINT [DF_TPDirectiveAD_FundAnnuityInd]  DEFAULT (0),
	[FundAnnuityAmt] [money] NULL CONSTRAINT [DF_TPDirectiveAD_FundAnnuityAmt]  DEFAULT (0),
	[AnnuityRegInsurer] [varchar](120) NULL,
	[AnnuityPolicyNum] [varchar](20) NULL,
	[FundPayAnnuityInd] [tinyint] NULL CONSTRAINT [DF_TPDirectiveAD_FundPayAnnuityInd]  DEFAULT (0),
	[FundRemainAnnuityAmt] [money] NULL CONSTRAINT [DF_TPDirectiveAD_FundRemainAnnuityAmt]  DEFAULT (0),
	[PublicSectorFromDt] [datetime] NULL,
	[PublicSectorToDt] [datetime] NULL,
	[PublicSectorAmt] [money] NULL,
	[PublicSectorTransferDt] [datetime] NULL,
	[UnclaimedBenefPrevTaxedAmt] [money] NULL,
	[CancelReason] [varchar](120) NULL,
	[EmailAddressAdministrator] [varchar](50) NULL,
	[TaxedTransferNonMemberSpouse] [money] NULL,
	[ParticipatingEmployerName] [varchar](120) NULL,
	[FSBNumber] [varchar](25) NULL,
	[AIPFDeemedContrib] [varchar](15) NULL,
	[NonResidentInd] [char](1) NULL DEFAULT ('N'),
	[ServRendOutsideRepInd] [char](1) NULL DEFAULT ('N'),
	[ServRendContribFundMonth] [varchar](15) NULL,
	[ServRendOutsideRepMonth] [varchar](15) NULL,
	[FormID] [int] NULL,
	[SourceCode] [char](4) NULL,
	[YearOfAssessment] [char](4) NULL,
	[Pre1March1998Amt] [money] NULL,
	[TrfAmt] [money] NULL,
	[MemFundContr] [money] NULL,
	[ExcContribAmt] [money] NULL,
	[TaxedTransfNonMembSpouse] [money] NULL,
	[ExemptServices] [money] NULL,
	[AIPFMemberContributions] [money] NULL,
	[AdminPenalty] [money] NULL,
 CONSTRAINT [PK_TPDirectiveAD] PRIMARY KEY CLUSTERED 
(
	[FORMADID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


